Repository Tejas1510/Hacking-Scripts, pull requests merged in 2021-06, with the labels that each got.

#335 Drum Kit Game Added
  Javascript/Drum Kit/README.md
  Javascript/Drum Kit/images/crash.png
  Javascript/Drum Kit/images/kick.png
  Javascript/Drum Kit/images/snare.png
  Javascript/Drum Kit/images/tom1.png
  Javascript/Drum Kit/images/tom2.png
  Javascript/Drum Kit/images/tom3.png
  Javascript/Drum Kit/images/tom4.png
  Javascript/Drum Kit/index.html
  Javascript/Drum Kit/index.js
  Javascript/Drum Kit/sounds/crash.mp3
  Javascript/Drum Kit/sounds/kick-bass.mp3
  Javascript/Drum Kit/sounds/snare.mp3
  Javascript/Drum Kit/sounds/tom-1.mp3
  Javascript/Drum Kit/sounds/tom-2.mp3
  Javascript/Drum Kit/sounds/tom-3.mp3
  Javascript/Drum Kit/sounds/tom-4.mp3
  Javascript/Drum Kit/styles.css
Labels: LGMSOC21, 🟨 Level2

#355 Add JARVIS(control OS) python script
  Python/JARVIS/JARVIS.py
  Python/JARVIS/README.md
  README.md
Labels: LGMSOC21, 🟧 Level3

#349 All Information About Country
  Python/All Information About Country/All information about Country.py
  Python/All Information About Country/README.md
Labels: LGMSOC21, 🟨 Level2

#353 Updated README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#370 Added Tic Tac Toe game in python
  Python/Tic-Tac-Toe/Images/1.png
  Python/Tic-Tac-Toe/Images/10.png
  Python/Tic-Tac-Toe/Images/2.png
  Python/Tic-Tac-Toe/Images/3.png
  Python/Tic-Tac-Toe/Images/4.png
  Python/Tic-Tac-Toe/Images/5.png
  Python/Tic-Tac-Toe/Images/6.png
  Python/Tic-Tac-Toe/Images/7.png
  Python/Tic-Tac-Toe/Images/8.png
  Python/Tic-Tac-Toe/Images/9.png
  Python/Tic-Tac-Toe/README.md
  Python/Tic-Tac-Toe/tic_tac_toe.py
Labels: LGMSOC21, 🟧 Level3

#358 Added JS Tip calculator.
  Javascript/Tip Calculator/index.html
  Javascript/Tip Calculator/readme.md
  Javascript/Tip Calculator/script.js
  Javascript/Tip Calculator/styles.css
Labels: LGMSOC21, 🟨 Level2

#369 Analog Clock using pure HTML,CSS and JS
  Javascript/Analog
  Javascript/Analog Clock/cg.png
  Javascript/Analog Clock/clock.png
  Javascript/Analog Clock/index.css
  Javascript/Analog Clock/index.html
  Javascript/Analog Clock/index.js
  Javascript/Clock
Labels: LGMSOC21, 🟨 Level2

#385 added a Guessing Game in C programmimg
  C/Guessing Game/Guessing-Game.c
  C/Guessing Game/README.md
  C/Guessing Game/Test.jpg
Labels: LGMSOC21, 🟨 Level2

#390 Facebook Messenger Automation
  Python/Facebook Messenger Automation/README.md
  Python/Facebook Messenger Automation/facebook_messenger_automation.py
Labels: LGMSOC21, 🟧 Level3

#380 Improve UI of C card in services section
  Project Website/assets/css/style.css
  readme.md
Labels: LGMSOC21, 🟨 Level2

#395 Added Diano Game in Java Script
  Javascript/Diano Game/bg.jpg
  Javascript/Diano Game/dino.png
  Javascript/Diano Game/dragon.png
  Javascript/Diano Game/fav.jpg
  Javascript/Diano Game/gameover.mp3
  Javascript/Diano Game/index.css
  Javascript/Diano Game/index.html
  Javascript/Diano Game/index.js
  Javascript/Diano Game/music.mp3
Labels: LGMSOC21, 🟧 Level3

#406 Grammar Correction
  Python/Grammar Correction/README.md
  Python/Grammar Correction/main.py
Labels: LGMSOC21, 🟧 Level3

#415 Added Gwen - a voice assistant created using Python.
  Python/Gwen - Voice Assistant/Gwen.png
  Python/Gwen - Voice Assistant/Gwen/Gwen.py
  Python/Gwen - Voice Assistant/Gwen/api.py
  Python/Gwen - Voice Assistant/Gwen/api.txt
  Python/Gwen - Voice Assistant/Gwen/browser.py
  Python/Gwen - Voice Assistant/Gwen/gmail.py
  Python/Gwen - Voice Assistant/Gwen/weather.py
  Python/Gwen - Voice Assistant/Gwen/youtube.py
  Python/Gwen - Voice Assistant/readme.md
Labels: LGMSOC21, 🟧 Level3

#417 Battle-ship GUI using python and tkinter
  Python/Battle-ship-game/Instructions.txt
  Python/Battle-ship-game/README.md
  Python/Battle-ship-game/Snshots/screen-1.png
  Python/Battle-ship-game/Snshots/screen-2.png
  Python/Battle-ship-game/Sounds/exp.wav
  Python/Battle-ship-game/Sounds/shot.mp3
  Python/Battle-ship-game/game.py
  Python/Battle-ship-game/header.jpg
  Python/Battle-ship-game/image.jpg
  Python/Battle-ship-game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#410 Ping-Pong Game
  Javascript/ping-pong/Images/1.PNG
  Javascript/ping-pong/Images/2.PNG
  Javascript/ping-pong/Readme.md
  Javascript/ping-pong/favicon-32x32.png
  Javascript/ping-pong/index.html
  Javascript/ping-pong/script.js
  Javascript/ping-pong/style.css
Labels: LGMSOC21, 🟧 Level3

#436 Fixed the readme file of Gwen in python scripts.
  Python/Gwen - Voice Assistant/Gwen/browser.py
  Python/Gwen - Voice Assistant/Gwen/gmail.py
  Python/Gwen - Voice Assistant/Gwen/youtube.py
  Python/Gwen - Voice Assistant/readme.md
Labels: LGMSOC21, 🟩 Level1

#405 Typing Speed Test
  Python/Typing Speed Test/Readme.md
  Python/Typing Speed Test/demo.gif
  Python/Typing Speed Test/images/background.jpg
  Python/Typing Speed Test/images/icon.png
  Python/Typing Speed Test/images/open.jpg
  Python/Typing Speed Test/typingTest.py
Labels: LGMSOC21, Python, 🟧 Level3

#434 Caterpillar Game GUI
  Python/Caterpillar Game GUI/README.md
  Python/Caterpillar Game GUI/main.py
Labels: LGMSOC21, 🟨 Level2

#444 Python automation to get Jokes, Poems, Quotes
  Python/Poem-Jokes-Quotes/Images/joke_img0.png
  Python/Poem-Jokes-Quotes/Images/joke_img1.png
  Python/Poem-Jokes-Quotes/Images/joke_img2.png
  Python/Poem-Jokes-Quotes/Images/joke_img3.png
  Python/Poem-Jokes-Quotes/Images/joke_img4.png
  Python/Poem-Jokes-Quotes/Images/poem_img0.png
  Python/Poem-Jokes-Quotes/Images/poem_img1.png
  Python/Poem-Jokes-Quotes/Images/quotes_img.png
  Python/Poem-Jokes-Quotes/Images/quotes_img0.png
  Python/Poem-Jokes-Quotes/Images/quotes_img1.png
  Python/Poem-Jokes-Quotes/Images/quotes_img2.png
  Python/Poem-Jokes-Quotes/README.md
  Python/Poem-Jokes-Quotes/jokes.py
  Python/Poem-Jokes-Quotes/poem.py
  Python/Poem-Jokes-Quotes/quotes.py
Labels: LGMSOC21, 🟧 Level3

#440 Made a Calculator using vanilla JS
  Javascript/CALCULATOR/README.md
  Javascript/CALCULATOR/Screenshot (112).png
  Javascript/CALCULATOR/bcal.jpg
  Javascript/CALCULATOR/calc.ico
  Javascript/CALCULATOR/index.html
  Javascript/CALCULATOR/index.js
  Javascript/CALCULATOR/style.css
Labels: LGMSOC21, 🟨 Level2

#455 Added Bubble Catcher Game in python
  Python/Bubble Catcher Game/README.md
  Python/Bubble Catcher Game/bubble_catcher.py
  Python/Bubble Catcher Game/images/1.jpg
  Python/Bubble Catcher Game/images/2.jpg
  Python/Bubble Catcher Game/images/3.jpg
  Python/Bubble Catcher Game/images/4.jpg
  Python/Bubble Catcher Game/images/bgimage.jpg
Labels: LGMSOC21, 🟧 Level3

#439 Added FaceRecognition Python Script using OpenCV
  Python/FaceRecognition/haarcascade_frontalface_default.xml
  Python/FaceRecognition/open_cv_video_face_recognition.py
  Python/FaceRecognition/output.png
  Python/FaceRecognition/readme.md
Labels: LGMSOC21, 🟧 Level3

#458 Made a Web Stopwatch using JavaScript
  Javascript/Stopwatch/README.md
  Javascript/Stopwatch/app.js
  Javascript/Stopwatch/bg/bg1stop.jpg
  Javascript/Stopwatch/bg/bg2stop.jpg
  Javascript/Stopwatch/bg/bg3stop.jpg
  Javascript/Stopwatch/bg/favstop.jpg
  Javascript/Stopwatch/index.html
  Javascript/Stopwatch/phone.css
  Javascript/Stopwatch/phone2.css
  Javascript/Stopwatch/style.css
Labels: LGMSOC21, 🟨 Level2

#465 Binary Search #425
  Python/Binary Search/Binary_Search.py
  Python/Binary Search/README.md
  Python/Binary Search/images/search1.PNG
  Python/Binary Search/images/search2.PNG
  Python/Binary Search/images/search3.PNG
Labels: LGMSOC21, Python, 🟨 Level2

#437 Added Game #419
  Python/Phrase Guessing Game/README.md
  Python/Phrase Guessing Game/images/img1.PNG
  Python/Phrase Guessing Game/images/img2.PNG
  Python/Phrase Guessing Game/images/img3.PNG
  Python/Phrase Guessing Game/images/img4.PNG
  Python/Phrase Guessing Game/images/img5.PNG
  Python/Phrase Guessing Game/images/img6.PNG
  Python/Phrase Guessing Game/images/img7.PNG
  Python/Phrase Guessing Game/phrase_game.py
  Python/Phrase Guessing Game/phrases.json
  Python/Phrase Guessing Game/wheel.json
Labels: LGMSOC21, 🟧 Level3

#464 Minesweeper Game
  Python/Minesweeper/README.md
  Python/Minesweeper/minesweeper.py
Labels: LGMSOC21, 🟧 Level3

#468 Twitter Data Streaming
  Python/Twitter-data-Streaming/README.md
  Python/Twitter-data-Streaming/mod.py
  Python/Twitter-data-Streaming/output_images/output1.jpeg
  Python/Twitter-data-Streaming/output_images/output2.jpeg
Labels: LGMSOC21, 🟨 Level2

#460 Added a Rock Paper Scissors Game in C folder
  C/RPS/README.md
  C/RPS/RPSgame.c
  C/RPS/resultOfGame.txt
Labels: LGMSOC21, 🟨 Level2

#474 Added Keyboard pressed key detector in C Script
  C/Keyboard Pressed Key Detector/Check Which key is pressed on keyboard.c
  C/Keyboard Pressed Key Detector/README.md
  C/Keyboard Pressed Key Detector/images/a.jpg
  C/Keyboard Pressed Key Detector/images/f10.jpg
  C/Keyboard Pressed Key Detector/images/f4.jpg
  C/Keyboard Pressed Key Detector/images/h.jpg
Labels: LGMSOC21, 🟨 Level2

#484 Fix #450 Added code for nQueens
  C++/nQueens/README.md
  C++/nQueens/main.cpp
Labels: LGMSOC21, 🟧 Level3

#477 Added calculator in java
  Java/Custom_Calculator/README.md
  Java/Custom_Calculator/calculator.java
Labels: LGMSOC21, 🟨 Level2

#448 Covid19 tracker application
  Python/Covid19-tracker-application/Covid19 tracker application.py
  Python/Covid19-tracker-application/Images/graph.PNG
  Python/Covid19-tracker-application/Images/window.PNG
  Python/Covid19-tracker-application/README.md
Labels: LGMSOC21, Python, 🟧 Level3

#476 HangMan Using Python
  Python/Hangman/Images/categories.PNG
  Python/Hangman/Images/guessing1.PNG
  Python/Hangman/Images/guessing2.PNG
  Python/Hangman/Images/guessing3.PNG
  Python/Hangman/Images/guessing4.PNG
  Python/Hangman/Images/hangman.PNG
  Python/Hangman/Images/loosing.PNG
  Python/Hangman/Images/playingAgain.PNG
  Python/Hangman/Images/winning.PNG
  Python/Hangman/README.md
  Python/Hangman/hangman.py
Labels: LGMSOC21, 🟨 Level2

#480 Added a time and Date feature
  Javascript/Notes App/README.md
  Javascript/Notes App/script.js
  Javascript/Notes App/style.css
Labels: LGMSOC21, 🟨 Level2

#457 Added a script to get map of any city
  Python/Map Finder/Screenshot.png
  Python/Map Finder/Screenshot2.png
  Python/Map Finder/map.py
  Python/Map Finder/readme.md
Labels: LGMSOC21, 🟧 Level3

#497 Fix #466 Github profile viewer added
  Javascript/github profile viewer/Enter.png
  Javascript/github profile viewer/No-User.png
  Javascript/github profile viewer/README.md
  Javascript/github profile viewer/User.png
  Javascript/github profile viewer/bootstrap.min.css
  Javascript/github profile viewer/bootstrap.min.js
  Javascript/github profile viewer/github-fav.png
  Javascript/github profile viewer/index.html
  Javascript/github profile viewer/scripts.js
  Javascript/github profile viewer/styles.css
Labels: Javascript, LGMSOC21, 🟧 Level3

#496 #446 Uploaded the password checker script
  Python/Password Checker/Images/Output.png
  Python/Password Checker/README.md
  Python/Password Checker/password_checker.py
  Python/Password Checker/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#478 Matchmaker Game
  Python/Matchmaker Game/README.md
  Python/Matchmaker Game/matchmaker_game.py
Labels: LGMSOC21, 🟨 Level2

#503 Brick Breaker Game
  Python/Brick Breaker Game/Images/img.png
  Python/Brick Breaker Game/README.md
  Python/Brick Breaker Game/brickBreakerGame.py
Labels: LGMSOC21, 🟧 Level3

#519 Fix #363
  Python/Towers_of_Hanoi/.DS_Store
  Python/Towers_of_Hanoi/README.md
  Python/Towers_of_Hanoi/assets/.DS_Store
  Python/Towers_of_Hanoi/assets/Game_start.png
  Python/Towers_of_Hanoi/assets/moving_elements.png
  Python/Towers_of_Hanoi/main.py
  Python/Towers_of_Hanoi/node.py
  Python/Towers_of_Hanoi/stack.py
Labels: LGMSOC21, 🟧 Level3

#495 Fix #441 Quick Sort Visualizer
  Python/Quick Sort Visualizer/README.md
  Python/Quick Sort Visualizer/script.py
Labels: LGMSOC21, 🟧 Level3

#522 Added Snakes and Ladders Game
  C++/Snakes and Ladders/Readme.md.txt
  C++/Snakes and Ladders/Snakes and Ladders.cpp
  C++/Snakes and Ladders/Snakes.jpg
Labels: LGMSOC21, 🟨 Level2

#520 Add Basic Calculator
  Python/Basic-calculator/README.md
  Python/Basic-calculator/calculator.py
  Python/Basic-calculator/image/1.jpg
  Python/Basic-calculator/image/2.jpg
  Python/Basic-calculator/image/3.jpg
  Python/Basic-calculator/image/4.jpg
  Python/Basic-calculator/image/5.jpg
Labels: LGMSOC21, 🟨 Level2

#538 tic tac toe game in java
  Java/Tic-Tac-Toe/Images/Tic_Tac_Toe.png
  Java/Tic-Tac-Toe/Images/tic tac toe positions.png
  Java/Tic-Tac-Toe/Images/tic1.png
  Java/Tic-Tac-Toe/Images/tic2.png
  Java/Tic-Tac-Toe/Images/tic3.png
  Java/Tic-Tac-Toe/Images/tic4.png
  Java/Tic-Tac-Toe/Images/tic5.png
  Java/Tic-Tac-Toe/README.md
  Java/Tic-Tac-Toe/Tic_Tac_Toe.java
Labels: LGMSOC21, 🟨 Level2

#530 Fix #489 Calculator reinvented using js
  Javascript/CALCULATOR/README.md
  Javascript/CALCULATOR/Screenshot (112).png
  Javascript/CALCULATOR/bcal.jpg
  Javascript/CALCULATOR/calc.ico
  Javascript/CALCULATOR/calci-favicon.png
  Javascript/CALCULATOR/calci.css
  Javascript/CALCULATOR/images/calculator.png
  Javascript/CALCULATOR/index.html
  Javascript/CALCULATOR/index.js
  Javascript/CALCULATOR/pattern-34.jpg
  Javascript/CALCULATOR/script.js
  Javascript/CALCULATOR/style.css
Labels: LGMSOC21, 🟧 Level3

#500 #490 Added Random Quote generator in JavaScript
  Javascript/Random-Quote-Generator/README.md
  Javascript/Random-Quote-Generator/index.html
  Javascript/Random-Quote-Generator/script.js
  Javascript/Random-Quote-Generator/style.css
Labels: LGMSOC21, 🟧 Level3

#555 Rock_Paper_Sciscor_C++
  C++/Readme.md
  C++/image.png
  C++/main.cpp
Labels: LGMSOC21, 🟨 Level2

#553 Fix #518 . Added LGMSOC logo under Open Source Program section in Readme.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#527 Insect-catch-game
  Javascript/insect-catch-game/Images/input.PNG
  Javascript/insect-catch-game/Images/input1.PNG
  Javascript/insect-catch-game/Images/output.PNG
  Javascript/insect-catch-game/Readme.md
  Javascript/insect-catch-game/index.html
  Javascript/insect-catch-game/script.js
  Javascript/insect-catch-game/style.css
Labels: LGMSOC21, 🟨 Level2

#534 Changed the styling of JavaScript/Counting days and fixed a bug in it
  Javascript/CountingDays/Readme.MD
  Javascript/CountingDays/images/bg-image.png
  Javascript/CountingDays/images/demo-image.png
  Javascript/CountingDays/images/image1.png
  Javascript/CountingDays/index.html
  Javascript/CountingDays/style.css
Labels: LGMSOC21, 🟩 Level1

#535 Sentiment Classifier #483
  Python/Sentiment Classifier/README.md
  Python/Sentiment Classifier/Sentiment_Classifier.py
  Python/Sentiment Classifier/images/image4.PNG
  Python/Sentiment Classifier/images/image5.PNG
  Python/Sentiment Classifier/images/image6.PNG
  Python/Sentiment Classifier/images/img1.PNG
  Python/Sentiment Classifier/images/img2.PNG
  Python/Sentiment Classifier/images/img3.PNG
  Python/Sentiment Classifier/negative_words.txt
  Python/Sentiment Classifier/positive_words.txt
  Python/Sentiment Classifier/project_twitter_data.csv
Labels: LGMSOC21, 🟧 Level3

#562 Madlibs Using Python
  Python/Madlibs/Images/Ouput1.png.png
  Python/Madlibs/Images/Output2.png.png
  Python/Madlibs/README.md
  Python/Madlibs/madlibs.py
Labels: LGMSOC21, 🟨 Level2

#568 Added moving car animation in JS
  Javascript/MovingCar/README.md
  Javascript/MovingCar/background.jpg
  Javascript/MovingCar/car_body.png
  Javascript/MovingCar/car_wheel_left.png
  Javascript/MovingCar/car_wheel_right.png
  Javascript/MovingCar/index.html
  Javascript/MovingCar/script.js
  Javascript/MovingCar/sound.mp3
  Javascript/MovingCar/style.css
  Javascript/MovingCar/track.png
  Javascript/MovingCar/trees.png
Labels: LGMSOC21, 🟨 Level2

#569 Voting System
  Python/Voting System/README.md
  Python/Voting System/voting_system.py
Labels: LGMSOC21, 🟨 Level2

#565 Time Zone Conversion
  Python/Time Zone Conversion/README.md
  Python/Time Zone Conversion/output.PNG
  Python/Time Zone Conversion/time_zone.py
Labels: LGMSOC21, 🟨 Level2

#548 #492 Added Ping Pong Game
  Python/Ping Pong Game/README.md
  Python/Ping Pong Game/ping-pong.py
  readme.md
Labels: LGMSOC21, 🟧 Level3

#560 #451 AnimeJin
  Javascript/AnimeJin/.gitignore
  Javascript/AnimeJin/Images/Genre.PNG
  Javascript/AnimeJin/Images/Homepage.PNG
  Javascript/AnimeJin/Images/Search.png
  Javascript/AnimeJin/README.md
  Javascript/AnimeJin/index.js
  Javascript/AnimeJin/package-lock.json
  Javascript/AnimeJin/package.json
  Javascript/AnimeJin/public/styles.css
  Javascript/AnimeJin/views/index.ejs
  Javascript/AnimeJin/views/partials/footer.ejs
  Javascript/AnimeJin/views/partials/header.ejs
  Javascript/AnimeJin/views/search.ejs
Labels: LGMSOC21, 🟨 Level2

#564 FIX #449 Mad Libs Generator
  C++/MAD_LIBS/main.cpp
  C++/MAD_LIBS/output.png
  C++/MAD_LIBS/readme.md
Labels: LGMSOC21, 🟩 Level1

#545 Add Bank Management Systems
  Python/Bank Managment Systems/Images/bank.PNG
  Python/Bank Managment Systems/Images/bank2.PNG
  Python/Bank Managment Systems/Images/bank3.PNG
  Python/Bank Managment Systems/README.md
  Python/Bank Managment Systems/backend.py
  Python/Bank Managment Systems/bankmanaging.db
  Python/Bank Managment Systems/frontend.py
Labels: LGMSOC21, 🟧 Level3

#546 Add Day_of_week script
  Python/Day_ofWeek/Day_of_week.py
  Python/Day_ofWeek/README.md
  Python/Day_ofWeek/snapshot.PNG
Labels: LGMSOC21, 🟩 Level1

#585 ATM Machine System
  Python/ATM Machine System/README.md
  Python/ATM Machine System/atm_machine_system.py
Labels: LGMSOC21, 🟨 Level2

#552 Implemented the auto complete feature in Dictionary in Python
  Python/Dictionary/README.md
  Python/Dictionary/dictionary.py
  Python/Dictionary/images/1.png
  Python/Dictionary/images/2.png
  Python/Dictionary/images/3.png
  Python/Dictionary/images/4.png
  Python/Dictionary/images/5.png
  Python/Dictionary/images/6.png
  Python/Dictionary/images/7.png
  Python/Dictionary/images/8.png
  Python/Dictionary/words.csv
Labels: LGMSOC21, 🟨 Level2

#581 #573 GUI-News-App
  Python/GUI-News-App/Images/nP.ico
  Python/GUI-News-App/README.md
  Python/GUI-News-App/Screenshots/img_1.png
  Python/GUI-News-App/Screenshots/img_2.png
  Python/GUI-News-App/news_app.py
Labels: LGMSOC21, 🟧 Level3

#563 #513 Adding PIP upgrade script
  Python/PIP Upgrade/Images/Output.png
  Python/PIP Upgrade/Images/Screenshot.png
  Python/PIP Upgrade/Readme.md
  Python/PIP Upgrade/pip_upgrade.py
  Python/PIP Upgrade/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#589 Added Image to Icon Converter in Python
  Python/Image to Icon Converter/Images/1.jpg
  Python/Image to Icon Converter/Images/2.jpg
  Python/Image to Icon Converter/Images/3.jpg
  Python/Image to Icon Converter/Images/4.jpg
  Python/Image to Icon Converter/Images/5.jpg
  Python/Image to Icon Converter/Images/6.jpg
  Python/Image to Icon Converter/Images/7.jpg
  Python/Image to Icon Converter/Images/8.jpg
  Python/Image to Icon Converter/README.md
  Python/Image to Icon Converter/image_to_icon_converter.py
  Python/Image to Icon Converter/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#605 Fixes #590, Morse code decryption script
  C++/Morse code decryption script/INPUT.txt
  C++/Morse code decryption script/OUTPUT.txt
  C++/Morse code decryption script/README.md
  C++/Morse code decryption script/images/ss-input.png
  C++/Morse code decryption script/images/ss-output.png
  C++/Morse code decryption script/morse.cpp
Labels: LGMSOC21, 🟨 Level2

#594 Create CoffeeMachine
  Java/Coffee Machine/CoffeeMachine.java
  Java/Coffee Machine/Images/five.png
  Java/Coffee Machine/Images/four.png
  Java/Coffee Machine/Images/one.png
  Java/Coffee Machine/Images/seven.png
  Java/Coffee Machine/Images/six.png
  Java/Coffee Machine/Images/three.png
  Java/Coffee Machine/Images/two.png
  Java/Coffee Machine/Readme.md
Labels: LGMSOC21, 🟨 Level2

#576 #322 : QR code generation in JAVA
  Java/QR-Code_Generator/GenerateQR.java
  Java/QR-Code_Generator/QRs/LGM-SOC.png
  Java/QR-Code_Generator/Readme.md
Labels: LGMSOC21, 🟨 Level2

#591 Currency Converter
  Python/Currency Converter/README.md
  Python/Currency Converter/currency
  Python/Currency Converter/currency converter.py
Labels: LGMSOC21, 🟨 Level2

#604 Fixes #554, Flappy bird game using js
  Javascript/Flappy bird game/README.md
  Javascript/Flappy bird game/flappy.jpg
  Javascript/Flappy bird game/images/ss.png
  Javascript/Flappy bird game/index.html
  Javascript/Flappy bird game/scripts.js
  Javascript/Flappy bird game/styles.css
Labels: LGMSOC21, 🟧 Level3

#615 Dice Game With Bot (Python)
  Python/Dice Game With Bot/Dice game with a bot.py
  Python/Dice Game With Bot/README.md
Labels: LGMSOC21, 🟩 Level1

#626 Fixes #600, GSoC Organization Scraper and Classifier
  Python/GSoC-Tech-Classifier/GSoC_Org_List.xlsx
  Python/GSoC-Tech-Classifier/GSoC_ScreenShot.PNG
  Python/GSoC-Tech-Classifier/README.md
  Python/GSoC-Tech-Classifier/gsoc-tech-classifier.py
  Python/GSoC-Tech-Classifier/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#611 Added Zodiac Sign Finder in Python
  Python/Zodiac Sign Finder/Images/1.jpg
  Python/Zodiac Sign Finder/Images/10.jpg
  Python/Zodiac Sign Finder/Images/11.jpg
  Python/Zodiac Sign Finder/Images/12.jpg
  Python/Zodiac Sign Finder/Images/13.jpg
  Python/Zodiac Sign Finder/Images/14.jpg
  Python/Zodiac Sign Finder/Images/15.jpg
  Python/Zodiac Sign Finder/Images/16.jpg
  Python/Zodiac Sign Finder/Images/17.jpg
  Python/Zodiac Sign Finder/Images/18.jpg
  Python/Zodiac Sign Finder/Images/19.jpg
  Python/Zodiac Sign Finder/Images/2.jpg
  Python/Zodiac Sign Finder/Images/3.jpg
  Python/Zodiac Sign Finder/Images/4.jpg
  Python/Zodiac Sign Finder/Images/5.jpg
  Python/Zodiac Sign Finder/Images/6.jpg
  Python/Zodiac Sign Finder/Images/7.jpg
  Python/Zodiac Sign Finder/Images/8.jpg
  Python/Zodiac Sign Finder/Images/9.jpg
  Python/Zodiac Sign Finder/Images/aquarius.gif
  Python/Zodiac Sign Finder/Images/aries.gif
  Python/Zodiac Sign Finder/Images/cancer.gif
  Python/Zodiac Sign Finder/Images/capricorn.gif
  Python/Zodiac Sign Finder/Images/gemini.gif
  Python/Zodiac Sign Finder/Images/leo.gif
  Python/Zodiac Sign Finder/Images/libra.gif
  Python/Zodiac Sign Finder/Images/pisces.gif
  Python/Zodiac Sign Finder/Images/sagittarius.gif
  Python/Zodiac Sign Finder/Images/scorpio.gif
  Python/Zodiac Sign Finder/Images/taurus.gif
  Python/Zodiac Sign Finder/Images/virgo.gif
  Python/Zodiac Sign Finder/Images/zodiac.jpg
  Python/Zodiac Sign Finder/README.md
  Python/Zodiac Sign Finder/requirements.txt
  Python/Zodiac Sign Finder/zodiac_sign_finder.py
Labels: LGMSOC21, 🟧 Level3

#596 Added javascript/MemoryGame
  Javascript/MemoryGame/.DS_Store
  Javascript/MemoryGame/README.md
  Javascript/MemoryGame/game.js
  Javascript/MemoryGame/images/Screenshot (2).png
  Javascript/MemoryGame/images/Screenshot (3).png
  Javascript/MemoryGame/images/Screenshot (4).png
  Javascript/MemoryGame/index.html
  Javascript/MemoryGame/sounds/blue.mp3
  Javascript/MemoryGame/sounds/green.mp3
  Javascript/MemoryGame/sounds/red.mp3
  Javascript/MemoryGame/sounds/wrong.mp3
  Javascript/MemoryGame/sounds/yellow.mp3
  Javascript/MemoryGame/styles.css
Labels: LGMSOC21, 🟨 Level2

#582 Added ToDoList App with Java
  Java/ToDoApp/Images/addTask.png
  Java/ToDoApp/Images/deleteTask.png
  Java/ToDoApp/Images/printTask.png
  Java/ToDoApp/Images/searchTask.png
  Java/ToDoApp/ToDo/ToDoApp.iml
  Java/ToDoApp/ToDo/src/com/paras/todoapp/dto/ToDoDTO.java
  Java/ToDoApp/ToDo/src/com/paras/todoapp/repo/IToDoRepo.java
  Java/ToDoApp/ToDo/src/com/paras/todoapp/repo/ToDoRepo.java
  Java/ToDoApp/ToDo/src/com/paras/todoapp/utils/Constants.java
  Java/ToDoApp/ToDo/src/com/paras/todoapp/utils/MessageReader.java
  Java/ToDoApp/ToDo/src/com/paras/todoapp/view/ToDoView.java
  Java/ToDoApp/ToDo/src/messages.properties
  Java/ToDoApp/ToDo/src/tasks.dat
  Java/ToDoApp/readme.md
Labels: LGMSOC21, 🟧 Level3

#593 Added a Python Script to convert a clear image to blur image.
  Python/Blur Image/blurredimage.jpg
  Python/Blur Image/clear_to_blur_image.py
  Python/Blur Image/input.png
  Python/Blur Image/photo.jpeg
  Python/Blur Image/readme.md
Labels: LGMSOC21, 🟩 Level1

#608 Added Internet Speed Test in Python
  Python/Internet Speed Test/Capture.PNG
  Python/Internet Speed Test/Readme.md
  Python/Internet Speed Test/speedgui.py
Labels: LGMSOC21, 🟩 Level1

#613 Quiz App using JS
  Javascript/quiz-app/Images/1.PNG
  Javascript/quiz-app/Images/2.PNG
  Javascript/quiz-app/Readme.md
  Javascript/quiz-app/index.html
  Javascript/quiz-app/script.js
  Javascript/quiz-app/style.css
Labels: LGMSOC21, 🟧 Level3

#597 Added few git commands in readme file
  readme.md
Labels: LGMSOC21, 🟩 Level1

#627 Fix #623 - Reddit Comment Bot
  Python/Reddit Comment Bot/Images/README.md
  Python/Reddit Comment Bot/Images/bot.png
  Python/Reddit Comment Bot/Images/bot2.png
  Python/Reddit Comment Bot/Images/input_bot.png
  Python/Reddit Comment Bot/README.md
  Python/Reddit Comment Bot/config.py
  Python/Reddit Comment Bot/reddit_comment_bot.py
  Python/Reddit Comment Bot/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#632 Animal quiz added
  Python/Animal_quiz/README.md
  Python/Animal_quiz/code.py
Labels: LGMSOC21, 🟨 Level2

#629 FIX #587 AIRLINE BOOKING SYSTEM
  C++/Airline_Booking_System/booking_system
  C++/Airline_Booking_System/booking_system.cpp
  C++/Airline_Booking_System/output.png
  C++/Airline_Booking_System/readme.md
Labels: LGMSOC21, 🟨 Level2

#639 Fixes #536 Rot-n encryption
  Javascript/Rot-N encryptor/README.md
  Javascript/Rot-N encryptor/images/rot.png
  Javascript/Rot-N encryptor/index.html
  Javascript/Rot-N encryptor/scripts.js
  Javascript/Rot-N encryptor/styles.css
Labels: Javascript, LGMSOC21, 🟨 Level2

#638 Added Missing Alphabet Game in Python
  Python/Missing Alphabet Game/Images/1.jpg
  Python/Missing Alphabet Game/Images/2.jpg
  Python/Missing Alphabet Game/Images/3.jpg
  Python/Missing Alphabet Game/Images/4.jpg
  Python/Missing Alphabet Game/Images/5.jpg
  Python/Missing Alphabet Game/Images/6.jpg
  Python/Missing Alphabet Game/Images/7.jpg
  Python/Missing Alphabet Game/Images/missing.jpg
  Python/Missing Alphabet Game/Images/score1.gif
  Python/Missing Alphabet Game/README.md
  Python/Missing Alphabet Game/country_name.csv
  Python/Missing Alphabet Game/missing_alphabet_game.py
  Python/Missing Alphabet Game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#646 Mobile Recharge Plan Detailer(Python)
  Python/Mobile Recharge Plan Detailer/README.md
  Python/Mobile Recharge Plan Detailer/main.py
Labels: LGMSOC21, 🟩 Level1

#625 Chatty Bot
  Python/Chatty Bot/Readme.md
  Python/Chatty Bot/chattybot.py
  Python/Chatty Bot/pictures/p1.png
  Python/Chatty Bot/pictures/p2.png
  Python/Chatty Bot/pictures/p3.png
Labels: LGMSOC21, 🟨 Level2

#643 QR Code Content Reader
  Python/QR_Code_Content/QR_code_content.py
  Python/QR_Code_Content/README.md
  Python/QR_Code_Content/Screenshot.png
Labels: LGMSOC21, 🟨 Level2

#634 Added the Image extractor file.
  Python/PDF/images/img.png
  Python/PDF/pdf.py
  Python/PDF/pdf_images/demo.pdf
  Python/PDF/pdf_images/page1_image1.jpeg
  Python/PDF/pdf_images/page1_image2.jpeg
  Python/PDF/pdf_images/page2_image1.jpeg
  Python/PDF/pdf_images/page2_image2.jpeg
  Python/PDF/readme.md
Labels: LGMSOC21, 🟨 Level2

#657 Added code for Scientific Calculator using Python and Tkinter
  Python/Scientific Calculator with GUI/README.md
  Python/Scientific Calculator with GUI/Results/Gui design.PNG
  Python/Scientific Calculator with GUI/Results/arithmetic input.PNG
  Python/Scientific Calculator with GUI/Results/arithmetic output.PNG
  Python/Scientific Calculator with GUI/Results/exponential input.PNG
  Python/Scientific Calculator with GUI/Results/exponential output.PNG
  Python/Scientific Calculator with GUI/Results/factorial input.PNG
  Python/Scientific Calculator with GUI/Results/factorial output.PNG
  Python/Scientific Calculator with GUI/Results/logarithmic input.PNG
  Python/Scientific Calculator with GUI/Results/logarithmic output.PNG
  Python/Scientific Calculator with GUI/Results/round input.PNG
  Python/Scientific Calculator with GUI/Results/round output.PNG
  Python/Scientific Calculator with GUI/Results/trigonometric input sin.PNG
  Python/Scientific Calculator with GUI/Results/trigonometric output sin.PNG
  Python/Scientific Calculator with GUI/scientific_calculator.py
Labels: LGMSOC21, 🟥 Level4

#660 Added Snakes and Ladders Game in python folder (Fixes issue #637)
  Python/Snakes and Ladders Game/Images/output.png
  Python/Snakes and Ladders Game/Images/snake-and-ladders.jpg
  Python/Snakes and Ladders Game/README.md
  Python/Snakes and Ladders Game/requirements.txt
  Python/Snakes and Ladders Game/snakes_and_ladders.py
Labels: LGMSOC21, 🟧 Level3

#666 Wifi Password Fetcher(GUI)
  Python/Wifi Password Fetcher(GUI)/README.md
  Python/Wifi Password Fetcher(GUI)/wifi_password_fetcher.py
Labels: LGMSOC21, 🟨 Level2

#598 Fix#558 (Make the Dice Game Competetive)
  Javascript/Dice/index.html
  Javascript/Dice/index.js
  Javascript/Dice/readme.md
  Javascript/Dice/styles.css
Labels: LGMSOC21, 🟨 Level2

#661 Added End Result Predictor in Tic Tac Toe game in Python Scripts
  Python/End Result Predictor in TIC TAC TOE/Images/1.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/10.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/11.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/2.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/3.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/4.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/5.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/6.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/7.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/8.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/9.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/board.png
  Python/End Result Predictor in TIC TAC TOE/Images/empty.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/o.jpg
  Python/End Result Predictor in TIC TAC TOE/Images/x.jpg
  Python/End Result Predictor in TIC TAC TOE/README.md
  Python/End Result Predictor in TIC TAC TOE/end_result_predictor.py
  Python/End Result Predictor in TIC TAC TOE/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#669 Added Spelling Corrector in Python Script
  Python/Spelling Corrector/Images/1.jpg
  Python/Spelling Corrector/Images/2.jpg
  Python/Spelling Corrector/Images/3.jpg
  Python/Spelling Corrector/Images/4.jpg
  Python/Spelling Corrector/Images/5.jpg
  Python/Spelling Corrector/Images/spell.jpg
  Python/Spelling Corrector/README.md
  Python/Spelling Corrector/requirements.txt
  Python/Spelling Corrector/spelling_corrector.py
Labels: LGMSOC21, 🟨 Level2

#672 Tracking Phone Number(Python)
  Python/Tracking Phone Number/README.md
  Python/Tracking Phone Number/tracking_phone_number.py
Labels: LGMSOC21, 🟨 Level2

#667 Caser Cipher #561
  C++/Cipher/Caser Ciper to Decrypt.cpp
  C++/Cipher/Caser Ciper to Encrypt.cpp
  C++/Cipher/Encrypt.jpg
  C++/Cipher/Readme.md
  C++/Cipher/decrypt.jpg
Labels: LGMSOC21, 🟨 Level2

#680 Fix #642 Guitar-Online added
  Javascript/Guitar-Online/README.md
  Javascript/Guitar-Online/audio files/A.mp3
  Javascript/Guitar-Online/audio files/B.mp3
  Javascript/Guitar-Online/audio files/D.mp3
  Javascript/Guitar-Online/audio files/E.mp3
  Javascript/Guitar-Online/audio files/G.mp3
  Javascript/Guitar-Online/audio files/e2.mp3
  Javascript/Guitar-Online/guitar.jpg
  Javascript/Guitar-Online/images/ss.png
  Javascript/Guitar-Online/index.html
  Javascript/Guitar-Online/scripts.js
  Javascript/Guitar-Online/styles.css
Labels: LGMSOC21, 🟨 Level2

#677 Library Management GUI
  Python/Library Management GUI/README.md
  Python/Library Management GUI/main.py
Labels: LGMSOC21, Python, 🟨 Level2

#699 Update Readme.MD
  Python/weatherscrapper/Readme.MD
Labels: LGMSOC21, 🟪 Level0

#697 gui calculator in java
  Java/GUI_Calculator/Images/calc1.png
  Java/GUI_Calculator/Images/calc2.png
  Java/GUI_Calculator/Images/calc3.png
  Java/GUI_Calculator/Images/calc4.png
  Java/GUI_Calculator/Images/calc5.png
  Java/GUI_Calculator/Images/calc6.png
  Java/GUI_Calculator/Images/calc7.png
  Java/GUI_Calculator/README.md
  Java/GUI_Calculator/calculator.java
Labels: LGMSOC21, 🟨 Level2

#689 Fetching Gold Price(Python)
  Python/Fetching Gold Price/README.md
  Python/Fetching Gold Price/main.py
Labels: LGMSOC21, 🟧 Level3

#700 fix #640 Chrome Dino game
  Javascript/Chrome Dino/README.md
  Javascript/Chrome Dino/images/ss.png
  Javascript/Chrome Dino/index.html
  Javascript/Chrome Dino/scripts.js
  Javascript/Chrome Dino/styles.css
Labels: LGMSOC21, 🟧 Level3

#710 Updated Time Zone Conversion in Python Scripts
  Python/Time Zone Conversion/Images/1.jpg
  Python/Time Zone Conversion/Images/2.jpg
  Python/Time Zone Conversion/Images/3.jpg
  Python/Time Zone Conversion/Images/4.jpg
  Python/Time Zone Conversion/Images/5.jpg
  Python/Time Zone Conversion/Images/6.jpg
  Python/Time Zone Conversion/Images/output.PNG
  Python/Time Zone Conversion/Images/time.gif
  Python/Time Zone Conversion/README.md
  Python/Time Zone Conversion/conversion.csv
  Python/Time Zone Conversion/requirements.txt
  Python/Time Zone Conversion/time_zone.py
Labels: LGMSOC21, 🟧 Level3

#696 Added Part Of Speech in Python
  Python/Part Of Speech Calculator/Images/1.jpg
  Python/Part Of Speech Calculator/Images/2.jpg
  Python/Part Of Speech Calculator/Images/3.jpg
  Python/Part Of Speech Calculator/Images/4.jpg
  Python/Part Of Speech Calculator/Images/5.jpg
  Python/Part Of Speech Calculator/README.md
  Python/Part Of Speech Calculator/part_of_speech_calculator.py
  Python/Part Of Speech Calculator/requirements.txt
  Python/Part Of Speeech Calculator/Images/1.jpg
  Python/Part Of Speeech Calculator/Images/2.jpg
  Python/Part Of Speeech Calculator/Images/3.jpg
  Python/Part Of Speeech Calculator/Images/4.jpg
  Python/Part Of Speeech Calculator/Images/5.jpg
  Python/Part Of Speeech Calculator/README.md
  Python/Part Of Speeech Calculator/part_of_speech_calculator.py
  Python/Part Of Speeech Calculator/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#683 Automate Screenshot function using Python
  Python/Automate_Screenshot/Automate_Screenshot.py
  Python/Automate_Screenshot/images/img1.png
  Python/Automate_Screenshot/images/img2.png
  Python/Automate_Screenshot/images/img3.png
  Python/Automate_Screenshot/images/img4.png
  Python/Automate_Screenshot/images/img5.png
  Python/Automate_Screenshot/readme.md
Labels: LGMSOC21, 🟩 Level1

#717 Real-time Petrol Price Finder(Python)
  Python/Real-time Petrol Price Finder/README.md
  Python/Real-time Petrol Price Finder/realtime petrol price.py
Labels: LGMSOC21, 🟩 Level1

#675 Fixed #668 : Fork Icon/Symbol Replaced
  README.md
  assets/forkIcon.JPG
Labels: LGMSOC21, 🟪 Level0

#722 Added Search Implementation in python
  Python/Search Implementation/Images/1.jpg
  Python/Search Implementation/Images/2.jpg
  Python/Search Implementation/Images/3.jpg
  Python/Search Implementation/Images/4.jpg
  Python/Search Implementation/Images/5.jpg
  Python/Search Implementation/Images/6.jpg
  Python/Search Implementation/Images/7.jpg
  Python/Search Implementation/README.md
  Python/Search Implementation/requirements.txt
  Python/Search Implementation/search_implementation.py
  Python/Search Implementation/words.csv
Labels: LGMSOC21, 🟧 Level3

#663 Fix #653 add Paint in c++
  C++/Paint-with-UG/README.md
  C++/Paint-with-UG/Screenshots/Screenshot 2021-02-09 215935.jpg
  C++/Paint-with-UG/Screenshots/Screenshot 2021-02-09 223034.jpg
  C++/Paint-with-UG/Screenshots/Screenshot 2021-02-09 223338.jpg
  C++/Paint-with-UG/Screenshots/Screenshot 2021-02-09 223744.jpg
  C++/Paint-with-UG/paint.cpp
Labels: LGMSOC21, 🟥 Level4

#740 Fix #726 Codeforces profile viewer
  Javascript/Codeforces profile viewer/README.md
  Javascript/Codeforces profile viewer/bootstrap.min.css
  Javascript/Codeforces profile viewer/bootstrap.min.js
  Javascript/Codeforces profile viewer/images/Enter.png
  Javascript/Codeforces profile viewer/images/No-User.png
  Javascript/Codeforces profile viewer/images/User.png
  Javascript/Codeforces profile viewer/images/asdf
  Javascript/Codeforces profile viewer/index.html
  Javascript/Codeforces profile viewer/scripts.js
  Javascript/Codeforces profile viewer/styles.css
Labels: Javascript, LGMSOC21, 🟧 Level3

#733 Flames Game
  Python/Flames Game/README.md
  Python/Flames Game/flames.py
Labels: LGMSOC21, 🟨 Level2

#743 Fix #143 Python README Files
  Python/Certificate_Generator/Readme.MD
  Python/Colortoblack/Readme.MD
  Python/MoorseCodeGenerator/Readme.MD
  Python/MorseCodeGenerator/Readme.MD
  Python/MorseCodeGenerator/decrypt.py
  Python/MorseCodeGenerator/encrypt.py
  Python/MorseCodeGenerator/images/image1.png
  Python/MorseCodeGenerator/images/image2.png
  Python/MorseCodeGenerator/morse.py
  Python/RestNotifier/Readme.MD
  Python/TextToSpeech/Readme.MD
  Python/WifiConnectionFinder/Readme.MD
Labels: LGMSOC21, 🟩 Level1

#721 Added JS Live word counter
  Javascript/Live Words Counter/index.html
  Javascript/Live Words Counter/readme.md
  Javascript/Live Words Counter/script.js
  Javascript/Live Words Counter/style.css
Labels: LGMSOC21, 🟧 Level3

#747 Added Indian Food Information in Python
  Python/Indian Food Information/Images/1.jpg
  Python/Indian Food Information/Images/2.jpg
  Python/Indian Food Information/Images/3.jpg
  Python/Indian Food Information/Images/4.jpg
  Python/Indian Food Information/Images/5.jpg
  Python/Indian Food Information/Images/6.jpg
  Python/Indian Food Information/Images/7.jpg
  Python/Indian Food Information/Images/food.gif
  Python/Indian Food Information/README.md
  Python/Indian Food Information/indian_food.csv
  Python/Indian Food Information/indian_food_information.py
  Python/Indian Food Information/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#735 adventure game updated
  Python/Text-Adventure-Game/README.md
  Python/Text-Adventure-Game/adventure.py
  Python/Text-Adventure-Game/output_images/output1.png
  Python/Text-Adventure-Game/output_images/output2.png
Labels: LGMSOC21, 🟨 Level2

#713 React js joke app added
  Reactjs/react-joke-app/.gitignore
  Reactjs/react-joke-app/README.md
  Reactjs/react-joke-app/package-lock.json
  Reactjs/react-joke-app/package.json
  Reactjs/react-joke-app/public/favicon.ico
  Reactjs/react-joke-app/public/index.html
  Reactjs/react-joke-app/public/logo192.png
  Reactjs/react-joke-app/public/logo512.png
  Reactjs/react-joke-app/public/manifest.json
  Reactjs/react-joke-app/public/robots.txt
  Reactjs/react-joke-app/src/App.css
  Reactjs/react-joke-app/src/App.js
  Reactjs/react-joke-app/src/components/Footer.js
  Reactjs/react-joke-app/src/components/Home.js
  Reactjs/react-joke-app/src/components/Joke.js
  Reactjs/react-joke-app/src/index.css
  Reactjs/react-joke-app/src/index.js
  Reactjs/react-joke-app/src/reportWebVitals.js
  Reactjs/react-joke-app/src/setupTests.js
Labels: LGMSOC21, 🟧 Level3

#754 Added Virtual keyboard in Python Scripts
  Python/Virtual Keyboard/Images/1.jpg
  Python/Virtual Keyboard/Images/2.jpg
  Python/Virtual Keyboard/Images/3.jpg
  Python/Virtual Keyboard/Images/4.jpg
  Python/Virtual Keyboard/Images/5.jpg
  Python/Virtual Keyboard/Images/6.jpg
  Python/Virtual Keyboard/Images/7.jpg
  Python/Virtual Keyboard/Images/keyboard.gif
  Python/Virtual Keyboard/README.md
  Python/Virtual Keyboard/requirements.txt
  Python/Virtual Keyboard/virtual_keyboard.py
Labels: LGMSOC21, 🟧 Level3

#752 Stock Analyser(Python)
  Python/Stock Analyser/README.md
  Python/Stock Analyser/main.py
Labels: LGMSOC21, 🟧 Level3

#723 Magic 8ball in Python
  Python/Magic8Ball/8ball.py
  Python/Magic8Ball/README.md
Labels: LGMSOC21, 🟧 Level3

#757 File Transfer
  Python/File Transfer/Images/file_transfer_client_ss.jpg
  Python/File Transfer/Images/file_transfer_server_ss_1.jpg
  Python/File Transfer/Images/file_transfer_server_ss_2.jpg
  Python/File Transfer/README.md
  Python/File Transfer/data.txt
  Python/File Transfer/file_transfer_client.py
  Python/File Transfer/file_transfer_server.py
Labels: LGMSOC21, 🟧 Level3

#736 Bounce Ball Game
  Python/Bounce Ball Game/Bounce Ball Game.py
  Python/Bounce Ball Game/Bounce Ball_Logo.png
  Python/Bounce Ball Game/Bounce Ball_SplashScreen.gif
  Python/Bounce Ball Game/Media/Bounce Ball_Functioning.mp4
  Python/Bounce Ball Game/Media/First Screen With Logo.png
  Python/Bounce Ball Game/Media/Game Screen.png
  Python/Bounce Ball Game/Media/GameOver Screen.png
  Python/Bounce Ball Game/Media/Pause Screen.png
  Python/Bounce Ball Game/Media/SplashScreen.png
  Python/Bounce Ball Game/Readme.md
  Python/Bounce Ball Game/requirements.txt
Labels: LGMSOC21, 🟥 Level4

#764 Fix #734 Add UG-Typing-Expert
  C++/UG Typing Expert/Readme.md
  C++/UG Typing Expert/UG Typing Expert.cpp
  C++/UG Typing Expert/dowload to use/Leaderboard.txt
  C++/UG Typing Expert/dowload to use/game.jpg
  C++/UG Typing Expert/dowload to use/images (2).jpg
  C++/UG Typing Expert/dowload to use/typing.jpeg
  C++/UG Typing Expert/dowload to use/ug.jpeg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 201712.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212639.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212734.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212806.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212831.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212851.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212912.jpg
  C++/UG Typing Expert/pics/Screenshot 2021-02-13 212938.jpg
Labels: LGMSOC21, 🟥 Level4

#766 Air Quality Detector(Python using API)
  Python/Air Quality Detector/README.md
  Python/Air Quality Detector/main.py
Labels: LGMSOC21, 🟨 Level2

#772 Added Shutdown your pc by voice command using python
  Python/Shutdown using voice/Automate_Shutdown.py
  Python/Shutdown using voice/Images/img.png
  Python/Shutdown using voice/readme.md
Labels: LGMSOC21, 🟨 Level2

#773 Added SpaceX Mission Detailer in Python Scriptd
  Python/SpaceX Mission Detailer/Images/1.jpg
  Python/SpaceX Mission Detailer/Images/2.jpg
  Python/SpaceX Mission Detailer/Images/3.jpg
  Python/SpaceX Mission Detailer/Images/4.jpg
  Python/SpaceX Mission Detailer/Images/5.jpg
  Python/SpaceX Mission Detailer/Images/6.jpg
  Python/SpaceX Mission Detailer/Images/7.jpg
  Python/SpaceX Mission Detailer/Images/spacex.gif
  Python/SpaceX Mission Detailer/README.md
  Python/SpaceX Mission Detailer/requirements.txt
  Python/SpaceX Mission Detailer/spaceX_data.csv
  Python/SpaceX Mission Detailer/spacex_mission_detailer.py
Labels: LGMSOC21, 🟧 Level3

#761 Added World GDP Ranking in Python Scripts
  Python/World Bank GDP Ranking/Images/1.jpg
  Python/World Bank GDP Ranking/Images/2.jpg
  Python/World Bank GDP Ranking/Images/3.jpg
  Python/World Bank GDP Ranking/Images/4.jpg
  Python/World Bank GDP Ranking/Images/5.jpg
  Python/World Bank GDP Ranking/Images/6.jpg
  Python/World Bank GDP Ranking/Images/7.jpg
  Python/World Bank GDP Ranking/Images/gdp.gif
  Python/World Bank GDP Ranking/README.md
  Python/World Bank GDP Ranking/gdp.csv
  Python/World Bank GDP Ranking/requirements.txt
  Python/World Bank GDP Ranking/world_bank_gdp_ranking.py
Labels: LGMSOC21, 🟧 Level3

#763 Added the files
  C/Converter_days/Output.jpg
  C/Converter_days/README.md
  C/Converter_days/main.c
Labels: LGMSOC21, 🟨 Level2

#780 Fix #748 rot-n decryptor
  Javascript/Rot-N decryptor/README.md
  Javascript/Rot-N decryptor/images/rot.png
  Javascript/Rot-N decryptor/index.html
  Javascript/Rot-N decryptor/scripts.js
  Javascript/Rot-N decryptor/styles.css
Labels: LGMSOC21, 🟧 Level3

#779 Added Highlight Selected Part of Text application in Python
  Python/Highlight Selected Part of Text/Images/1.jpg
  Python/Highlight Selected Part of Text/Images/2.jpg
  Python/Highlight Selected Part of Text/Images/3.jpg
  Python/Highlight Selected Part of Text/Images/4.jpg
  Python/Highlight Selected Part of Text/Images/5.jpg
  Python/Highlight Selected Part of Text/Images/6.jpg
  Python/Highlight Selected Part of Text/README.md
  Python/Highlight Selected Part of Text/highlight_selected_part_of_text.py
  Python/Highlight Selected Part of Text/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#774 Bitcoin Price Tracker
  Python/Bitcoin Price Tracker/README.md
  Python/Bitcoin Price Tracker/main.py
Labels: LGMSOC21, 🟨 Level2

#759 added age calculator application using python
  Python/Age Calculator/README.md
  Python/Age Calculator/age_calculator.py
Labels: LGMSOC21, 🟧 Level3

#778 Fix #686 Falling ball game added
  Javascript/Falling Ball/Readme.md
  Javascript/Falling Ball/img1.png
  Javascript/Falling Ball/img2.png
  Javascript/Falling Ball/img3.png
  Javascript/Falling Ball/index.html
  Javascript/Falling Ball/script.js
  Javascript/Falling Ball/style.css
Labels: LGMSOC21, 🟧 Level3

#785 Fix # 765 Add Queue Visualizer
  C++/Queue-Visualizer/README.md
  C++/Queue-Visualizer/queue visualizer.cpp
  C++/Queue-Visualizer/screenshots/1.jpg
  C++/Queue-Visualizer/screenshots/2.jpg
  C++/Queue-Visualizer/screenshots/3.jpg
Labels: LGMSOC21, 🟥 Level4

#776 'how to' type qus using voice
  Python/Ask How to Qus using Voice/Images/howtoqus1.png
  Python/Ask How to Qus using Voice/Images/howtoqus2.png
  Python/Ask How to Qus using Voice/Images/howtoqus3.png
  Python/Ask How to Qus using Voice/Images/howtoqus4.png
  Python/Ask How to Qus using Voice/README.md
  Python/Ask How to Qus using Voice/how_to.py
  Python/Ask How to Qus using Voice/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#782 Added Periodic Table Elements Information in Python Script
  Python/Periodic Table Elements Information/Images/1.jpg
  Python/Periodic Table Elements Information/Images/2.jpg
  Python/Periodic Table Elements Information/Images/3.jpg
  Python/Periodic Table Elements Information/Images/4.jpg
  Python/Periodic Table Elements Information/Images/5.jpg
  Python/Periodic Table Elements Information/Images/6.jpg
  Python/Periodic Table Elements Information/Images/periodic.gif
  Python/Periodic Table Elements Information/README.md
  Python/Periodic Table Elements Information/periodic_table.csv
  Python/Periodic Table Elements Information/periodic_table_elements_information.py
  Python/Periodic Table Elements Information/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#788 Added Turtle Racing using Python
  Python/Turtle Racing/Images/img1.png
  Python/Turtle Racing/Images/img2.png
  Python/Turtle Racing/Images/img3.png
  Python/Turtle Racing/Turtle_race.py
  Python/Turtle Racing/readme.md
Labels: LGMSOC21, 🟨 Level2

#787 Added Indian University NIRF Ranking in Python Scripts
  Python/Indian University NIRF Ranking/Images/1.jpg
  Python/Indian University NIRF Ranking/Images/2.jpg
  Python/Indian University NIRF Ranking/Images/3.jpg
  Python/Indian University NIRF Ranking/Images/4.jpg
  Python/Indian University NIRF Ranking/Images/5.jpg
  Python/Indian University NIRF Ranking/Images/6.jpg
  Python/Indian University NIRF Ranking/Images/7.jpg
  Python/Indian University NIRF Ranking/Images/8.jpg
  Python/Indian University NIRF Ranking/Images/university.gif
  Python/Indian University NIRF Ranking/README.md
  Python/Indian University NIRF Ranking/engineering.csv
  Python/Indian University NIRF Ranking/indian_university_NIRF_ranking.py
  Python/Indian University NIRF Ranking/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#793 Added Pincodes of Indian City in Python Scripts
  Python/Pincodes of Indian City/Images/1.jpg
  Python/Pincodes of Indian City/Images/2.jpg
  Python/Pincodes of Indian City/Images/3.jpg
  Python/Pincodes of Indian City/Images/4.jpg
  Python/Pincodes of Indian City/Images/5.jpg
  Python/Pincodes of Indian City/Images/6.jpg
  Python/Pincodes of Indian City/Images/7.jpg
  Python/Pincodes of Indian City/Images/8.jpg
  Python/Pincodes of Indian City/Images/pincodes.gif
  Python/Pincodes of Indian City/README.md
  Python/Pincodes of Indian City/pincode_data.csv
  Python/Pincodes of Indian City/pincodes_of_indian_city.py
  Python/Pincodes of Indian City/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#797 Added Indian Trains Railway Details in Python Scripts
  Python/Indian Trains Details/All_Indian_Trains.csv
  Python/Indian Trains Details/Images/1.jpg
  Python/Indian Trains Details/Images/2.jpg
  Python/Indian Trains Details/Images/3.jpg
  Python/Indian Trains Details/Images/4.jpg
  Python/Indian Trains Details/Images/5.jpg
  Python/Indian Trains Details/Images/6.jpg
  Python/Indian Trains Details/Images/7.jpg
  Python/Indian Trains Details/Images/8.jpg
  Python/Indian Trains Details/Images/9.jpg
  Python/Indian Trains Details/Images/trains.gif
  Python/Indian Trains Details/README.md
  Python/Indian Trains Details/indian_trains_details.py
  Python/Indian Trains Details/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#739 Fixes #574 : Added Movie Info script which show information of movies through API
  Javascript/Movie Info/Readme.md
  Javascript/Movie Info/Screenshot/Screenshot 2021-06-22 095906.jpg
  Javascript/Movie Info/Screenshot/Screenshot 2021-06-22 100249.jpg
  Javascript/Movie Info/Screenshot/Screenshot 2021-06-22 100509.jpg
  Javascript/Movie Info/bootstrap.min.css
  Javascript/Movie Info/index.html
  Javascript/Movie Info/main-min.js
  Javascript/Movie Info/movie-min.html
  Javascript/Movie Info/style-min.css
Labels: LGMSOC21, 🟧 Level3

#799 Fix #786 GUI Sign Up Application
  C++/Sign Up Application/README.md
  C++/Sign Up Application/SignUP.jpg
  C++/Sign Up Application/src/Img/America.png
  C++/Sign Up Application/src/Img/Austriala.png
  C++/Sign Up Application/src/Img/India.png
  C++/Sign Up Application/src/Img/Nepal.jpg
  C++/Sign Up Application/src/Img/Russia.jpg
  C++/Sign Up Application/src/Img/bangladesh.png
  C++/Sign Up Application/src/Img/england.png
  C++/Sign Up Application/src/Img/switzerland.png
  C++/Sign Up Application/src/Sign_up_app.pro
  C++/Sign Up Application/src/Sign_up_app.pro.user
  C++/Sign Up Application/src/domain_name.txt
  C++/Sign Up Application/src/main.cpp
  C++/Sign Up Application/src/mainwindow.cpp
  C++/Sign Up Application/src/mainwindow.h
  C++/Sign Up Application/src/mainwindow.ui
  C++/Sign Up Application/src/src.qrc
Labels: LGMSOC21, 🟧 Level3

#801 Instagram Bot (Python)
  Python/Instagram Bot/README.md
  Python/Instagram Bot/instagram_bot.py
Labels: LGMSOC21, 🟧 Level3

#803 Added Creative design in python
  Python/Design in Turtle/Images/img1.png
  Python/Design in Turtle/Images/img2.png
  Python/Design in Turtle/Images/img3.png
  Python/Design in Turtle/Turtle_Design.py
  Python/Design in Turtle/readme.md
Labels: LGMSOC21, 🟨 Level2

#809 Fix #805 - Added JS virtual keyboard
  Javascript/Virtual Keyboard/README.md
  Javascript/Virtual Keyboard/index.html
  Javascript/Virtual Keyboard/script.js
  Javascript/Virtual Keyboard/style.css
Labels: LGMSOC21, 🟥 Level4

#813 Added World Companies Detailer in Python Scripts
  Python/World Companies Detailer/Images/1.jpg
  Python/World Companies Detailer/Images/2.jpg
  Python/World Companies Detailer/Images/3.jpg
  Python/World Companies Detailer/Images/4.jpg
  Python/World Companies Detailer/Images/5.jpg
  Python/World Companies Detailer/Images/6.jpg
  Python/World Companies Detailer/Images/7.jpg
  Python/World Companies Detailer/Images/8.jpg
  Python/World Companies Detailer/Images/9.jpg
  Python/World Companies Detailer/Images/company.gif
  Python/World Companies Detailer/README.md
  Python/World Companies Detailer/requirements.txt
  Python/World Companies Detailer/world_companies.csv
  Python/World Companies Detailer/world_companies_detailer.py
Labels: LGMSOC21, Python, 🟧 Level3

#812 To Do List GUI
  Python/To Do List GUI/Images/complete.jpg
  Python/To Do List GUI/Images/new_task.jpg
  Python/To Do List GUI/Images/scheduled.jpg
  Python/To Do List GUI/README.md
  Python/To Do List GUI/app.py
  Python/To Do List GUI/main.ui
  Python/To Do List GUI/main_window.py
  Python/To Do List GUI/new_task.py
  Python/To Do List GUI/new_task.ui
Labels: LGMSOC21, 🟧 Level3

#810 Excel File Automation(Python)
  Python/Excel File Automation/NewGrades.xlsx
  Python/Excel File Automation/README.md
  Python/Excel File Automation/excel_file_automation.py
Labels: LGMSOC21, 🟨 Level2

#818 Added Bermuda Triangle Incidents under Python Scripts
  Python/Bermuda Triangle Incidents/Images/1.jpg
  Python/Bermuda Triangle Incidents/Images/2.jpg
  Python/Bermuda Triangle Incidents/Images/3.jpg
  Python/Bermuda Triangle Incidents/Images/4.jpg
  Python/Bermuda Triangle Incidents/Images/5.jpg
  Python/Bermuda Triangle Incidents/Images/6.jpg
  Python/Bermuda Triangle Incidents/Images/7.jpg
  Python/Bermuda Triangle Incidents/Images/8.jpg
  Python/Bermuda Triangle Incidents/Images/bermuda.gif
  Python/Bermuda Triangle Incidents/README.md
  Python/Bermuda Triangle Incidents/bermuda_incidents.json
  Python/Bermuda Triangle Incidents/bermuda_triangle_incidents.py
  Python/Bermuda Triangle Incidents/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#820 Added Create Bargraph using python
  Python/Bar graph/Bar_Graph.py
  Python/Bar graph/Images/img1.png
  Python/Bar graph/Images/img2.png
  Python/Bar graph/Images/img3.png
  Python/Bar graph/readme.md
Labels: LGMSOC21, 🟩 Level1

#815 Weather Updates(Python)
  Python/Weather Updates/README.md
  Python/Weather Updates/weather_updates.py
Labels: LGMSOC21, 🟨 Level2
