Repository Tejas1510/Hacking-Scripts, pull requests merged in 2021-08, with the labels that each got.

#1047 Folder Content Sorter (Python)
  Python/Folder Content Sorter/README.md
  Python/Folder Content Sorter/folder_content_sorter.py
Labels: LGMSOC21, 🟧 Level3

#1044 Marvel API (Python)
  Python/Marvel API/README.md
  Python/Marvel API/marvel_api.py
Labels: 🟩 Level1

#1048 Added Image Encryption Decryption in Python Scripts
  Python/Image Encryption Decryption/Images/1.jpg
  Python/Image Encryption Decryption/Images/10.jpg
  Python/Image Encryption Decryption/Images/11.jpg
  Python/Image Encryption Decryption/Images/2.jpg
  Python/Image Encryption Decryption/Images/3.jpg
  Python/Image Encryption Decryption/Images/4.jpg
  Python/Image Encryption Decryption/Images/5.jpg
  Python/Image Encryption Decryption/Images/6.jpg
  Python/Image Encryption Decryption/Images/7.jpg
  Python/Image Encryption Decryption/Images/8.jpg
  Python/Image Encryption Decryption/Images/9.jpg
  Python/Image Encryption Decryption/README.md
  Python/Image Encryption Decryption/image_encryption_decryption.py
  Python/Image Encryption Decryption/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#1046 Document_Summarizer
  Python/Document_Summarizer/.DS_Store
  Python/Document_Summarizer/main.py
  Python/Document_Summarizer/origin_text.txt
  Python/Document_Summarizer/origin_text_summary.txt
  Python/Document_Summarizer/readme.md
Labels: LGMSOC21, 🟨 Level2

#1051 Snowfall Filter On Image (Python)
  Python/Snowfall Filter On Image/README.md
  Python/Snowfall Filter On Image/snowfall_filter_on_image.py
Labels: LGMSOC21, 🟨 Level2

#1055 Bank Data Finder (Python)
  Python/Bank Data Finder/README.md
  Python/Bank Data Finder/bank_data_finder.py
Labels: LGMSOC21, 🟧 Level3

#982 Added Latitude-Longitude Pair Verifier in Python Scripts
  Python/Latitude-Longitude Pair Verifier/Images/1.jpg
  Python/Latitude-Longitude Pair Verifier/Images/10.jpg
  Python/Latitude-Longitude Pair Verifier/Images/11.jpg
  Python/Latitude-Longitude Pair Verifier/Images/2.jpg
  Python/Latitude-Longitude Pair Verifier/Images/3.jpg
  Python/Latitude-Longitude Pair Verifier/Images/4.jpg
  Python/Latitude-Longitude Pair Verifier/Images/5.jpg
  Python/Latitude-Longitude Pair Verifier/Images/6.jpg
  Python/Latitude-Longitude Pair Verifier/Images/7.jpg
  Python/Latitude-Longitude Pair Verifier/Images/8.jpg
  Python/Latitude-Longitude Pair Verifier/Images/9.jpg
  Python/Latitude-Longitude Pair Verifier/Images/latlong.gif
  Python/Latitude-Longitude Pair Verifier/README.md
  Python/Latitude-Longitude Pair Verifier/latitude-longitude_pair_verifier.py
  Python/Latitude-Longitude Pair Verifier/requirements.txt
  Python/Latitude-Longitude Pair Verifier/world_location.csv
Labels: LGMSOC21, 🟨 Level2

#967 Add a Tic Tac Toe Game with better UI
  Javascript/Tic Tac Toe Game/index.html
  Javascript/Tic Tac Toe Game/readme.md
  Javascript/Tic Tac Toe Game/script.js
  Javascript/Tic Tac Toe Game/style.css
Labels: LGMSOC21, 🟧 Level3

#1056 Added Video Stitching in Python Scripts
  Python/Video Stitching/Images/1.jpg
  Python/Video Stitching/Images/10.jpg
  Python/Video Stitching/Images/11.jpg
  Python/Video Stitching/Images/2.jpg
  Python/Video Stitching/Images/3.jpg
  Python/Video Stitching/Images/4.jpg
  Python/Video Stitching/Images/5.jpg
  Python/Video Stitching/Images/6.jpg
  Python/Video Stitching/Images/7.jpg
  Python/Video Stitching/Images/8.jpg
  Python/Video Stitching/Images/9.jpg
  Python/Video Stitching/Images/vid_stitch.jpg
  Python/Video Stitching/README.md
  Python/Video Stitching/requirements.txt
  Python/Video Stitching/video_stitching.py
Labels: LGMSOC21, 🟧 Level3

#1059 red black tree insertion
  C++/redblacktree/Readme.md
  C++/redblacktree/output.png
  C++/redblacktree/redblacktree_insertion.cpp
Labels: LGMSOC21, 🟧 Level3

#1061 Password Generator
  Python/Password Generator/Images/pass_generator1.png
  Python/Password Generator/Images/pass_generator2.png
  Python/Password Generator/Images/pass_generator3.png
  Python/Password Generator/README.md
  Python/Password Generator/pass_generator.py
  Python/Password Generator/requirements.txt
Labels: 🟨 Level2, LGMSOC21

#1062 Added Image Snipper in Python Scripts
  Python/Image Snipper/Images/1.jpg
  Python/Image Snipper/Images/2.jpg
  Python/Image Snipper/Images/3.jpg
  Python/Image Snipper/Images/4.jpg
  Python/Image Snipper/Images/5.jpg
  Python/Image Snipper/Images/6.jpg
  Python/Image Snipper/Images/7.jpg
  Python/Image Snipper/Images/front.jpg
  Python/Image Snipper/Images/second.jpg
  Python/Image Snipper/README.md
  Python/Image Snipper/image_snipper.py
  Python/Image Snipper/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#1063 Snapchat Filters
  Python/Snapchat Filters/Images/ImageWithGoggles.png
  Python/Snapchat Filters/Images/Snapchat_Filtered.png
  Python/Snapchat Filters/Images/chris hems img.jpg
  Python/Snapchat Filters/Images/sunglasses.png
  Python/Snapchat Filters/README.md
  Python/Snapchat Filters/requirements.txt
  Python/Snapchat Filters/snapchat_filters.ipynb
Labels: LGMSOC21, 🟧 Level3
