Repository Tejas1510/Hacking-Scripts, pull requests merged in 2021-01, with the labels that each got.

#36 Just made a password generator using JS
  Javascript/Password Generator/OutputPassGeneratorScreenshot.PNG
  Javascript/Password Generator/README.md
  Javascript/Password Generator/index.html
  Javascript/Password Generator/main.js
  Javascript/Password Generator/style.css
Labels: Changes-requested

#10 Url shortner created
  URLShortner/README.md
  URLShortner/shortner.py
Labels: Python, assigned, easy, swoc2021

#59 Create basic GUI calculator
  Python/basic GUI calculator
Labels: in review

#68 issue #35
  Javascript/Number Guessing Game/images/comp.jpg
  Javascript/Number Guessing Game/images/logo.jpg
  Javascript/Number Guessing Game/images/user.jpg
  Javascript/Number Guessing Game/index.html
  Javascript/Number Guessing Game/index.js
  Javascript/Number Guessing Game/readme.md
  Javascript/Number Guessing Game/screenshots/computer.png
  Javascript/Number Guessing Game/screenshots/preview.png
  Javascript/Number Guessing Game/screenshots/user-1.png
  Javascript/Number Guessing Game/screenshots/user-2.png
  Javascript/Number Guessing Game/screenshots/user-3.png
  Javascript/Number Guessing Game/style.css
Labels: Changes-requested

#132 Dice Rolling Simulator using Python
  Python/Dice Rolling Simulator using Python/README.md
  Python/Dice Rolling Simulator using Python/program.py
Labels: Changes-requested

#146 dice simulator in js
  Javascript/Dice/.DS_Store
  Javascript/Dice/1..png
  Javascript/Dice/2..png
  Javascript/Dice/images/dice1.png
  Javascript/Dice/images/dice2.png
  Javascript/Dice/images/dice3.png
  Javascript/Dice/images/dice4.png
  Javascript/Dice/images/dice5.png
  Javascript/Dice/images/dice6.png
  Javascript/Dice/index.html
  Javascript/Dice/index.js
  Javascript/Dice/readme.md
  Javascript/Dice/styles.css
Labels: Changes-requested

#149 added music player game
  Javascript/music player/README.md
  Javascript/music player/css/musicplayer.css
  Javascript/music player/images/game.png
  Javascript/music player/images/game2.png
  Javascript/music player/js/musicplayer.js
  Javascript/music player/music_player.html
  Javascript/music player/sounds/bubbles.mp3
  Javascript/music player/sounds/clay.mp3
  Javascript/music player/sounds/confetti.mp3
  Javascript/music player/sounds/glimmer.mp3
  Javascript/music player/sounds/moon.mp3
  Javascript/music player/sounds/ufo.mp3
Labels: Changes-requested

#161 Added BMI Calculator App
  Python/BMI_GUI/README.md
  Python/BMI_GUI/app.py
Labels: Changes-requested

#201 Pokedex
  Javascript/Pokedex/Output 1.pdf
  Javascript/Pokedex/Output 2.pdf
  Javascript/Pokedex/README.md
  Javascript/Pokedex/index.html
  Javascript/Pokedex/script.js
  Javascript/Pokedex/style.css
Labels: Changes-requested
