Repository Tejas1510/Hacking-Scripts, pull requests merged in 2021-07, with the labels that each got.

#845 Added Fruit Ninja Game
  Python/Fruit Ninja Game/Media/FirstScreen.png
  Python/Fruit Ninja Game/Media/Functioning.mp4
  Python/Fruit Ninja Game/Media/GameOverScreen.png
  Python/Fruit Ninja Game/Media/GameScreen.png
  Python/Fruit Ninja Game/Media/background.png
  Python/Fruit Ninja Game/Media/bomb.png
  Python/Fruit Ninja Game/Media/explosion.png
  Python/Fruit Ninja Game/Media/half_melon.png
  Python/Fruit Ninja Game/Media/half_orange.png
  Python/Fruit Ninja Game/Media/half_pear.png
  Python/Fruit Ninja Game/Media/half_pomegranate.png
  Python/Fruit Ninja Game/Media/melon.png
  Python/Fruit Ninja Game/Media/orange.png
  Python/Fruit Ninja Game/Media/pear.png
  Python/Fruit Ninja Game/Media/pomegranate.png
  Python/Fruit Ninja Game/Media/red_lives.png
  Python/Fruit Ninja Game/README.md
  Python/Fruit Ninja Game/fontdesign.ttf
  Python/Fruit Ninja Game/fruit_ninja.py
  Python/Fruit Ninja Game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#847 Word Transfer
  Python/Word Transfer/Images/word_transfer_client_ss_1.jpg
  Python/Word Transfer/Images/word_transfer_client_ss_2.jpg
  Python/Word Transfer/Images/word_transfer_server_ss.jpg
  Python/Word Transfer/README.md
  Python/Word Transfer/word_tansfer_server.py
  Python/Word Transfer/word_transfer_client.py
Labels: LGMSOC21, 🟨 Level2

#859 Website Checker (Python)
  Python/Website Checker/README.md
  Python/Website Checker/website_checker.py
Labels: LGMSOC21, 🟩 Level1

#865 Bruteforce Attack (Python)
  Python/Bruteforce Attack/Bruteforce attack.py
  Python/Bruteforce Attack/README.md
Labels: LGMSOC21, 🟩 Level1

#862 Fix 844 Add Car Zone
  C++/Car-Zone/README.md
  C++/Car-Zone/car racing game.cpp
Labels: LGMSOC21, 🟥 Level4

#875 Fix #842 Color picker
  Javascript/RGB to Color/README.md
  Javascript/RGB to Color/images/ss.png
  Javascript/RGB to Color/index.html
  Javascript/RGB to Color/scripts.js
  Javascript/RGB to Color/styles.css
Labels: LGMSOC21, 🟧 Level3

#873 Added All Camera Model Detailer in Python Scripts
  Python/All Camera Model Detailer/Images/1.jpg
  Python/All Camera Model Detailer/Images/2.jpg
  Python/All Camera Model Detailer/Images/3.jpg
  Python/All Camera Model Detailer/Images/4.jpg
  Python/All Camera Model Detailer/Images/5.jpg
  Python/All Camera Model Detailer/Images/6.jpg
  Python/All Camera Model Detailer/Images/7.jpg
  Python/All Camera Model Detailer/Images/cameras.gif
  Python/All Camera Model Detailer/README.md
  Python/All Camera Model Detailer/all_camera_model_detailer.py
  Python/All Camera Model Detailer/camera_dataset.csv
  Python/All Camera Model Detailer/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#877 Checklist App (Python GUI)
  Python/Checklist App/README.md
  Python/Checklist App/main.py
  checklist.txt
Labels: LGMSOC21, 🟧 Level3

#891 Added 1300 Laptops in Python Scripts
  Python/1300 Laptops/1300_laptops.py
  Python/1300 Laptops/Images/1.jpg
  Python/1300 Laptops/Images/2.jpg
  Python/1300 Laptops/Images/3.jpg
  Python/1300 Laptops/Images/4.jpg
  Python/1300 Laptops/Images/5.jpg
  Python/1300 Laptops/Images/6.jpg
  Python/1300 Laptops/Images/7.jpg
  Python/1300 Laptops/Images/laptops.gif
  Python/1300 Laptops/README.md
  Python/1300 Laptops/laptop_dataset.csv
  Python/1300 Laptops/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#893 Added Convert photo to black and white photo using python
  Python/Black and White/BlackAndWhite.py
  Python/Black and White/Images/bw_img.jpg
  Python/Black and White/Images/img.jpg
  Python/Black and White/readme.md
Labels: LGMSOC21, 🟨 Level2

#881 Apple Store
  Python/Apple Store/Images/front_page.jpg
  Python/Apple Store/Images/login_page.jpg
  Python/Apple Store/Images/market_page.jpg
  Python/Apple Store/Images/purchase_item.jpg
  Python/Apple Store/README.md
  Python/Apple Store/market/__init__.py
  Python/Apple Store/market/forms.py
  Python/Apple Store/market/market.db
  Python/Apple Store/market/models.py
  Python/Apple Store/market/routes.py
  Python/Apple Store/market/templates/base.html
  Python/Apple Store/market/templates/home.html
  Python/Apple Store/market/templates/includes/items_modals.html
  Python/Apple Store/market/templates/includes/owned_items_modals.html
  Python/Apple Store/market/templates/login.html
  Python/Apple Store/market/templates/market.html
  Python/Apple Store/market/templates/register.html
  Python/Apple Store/run.py
Labels: LGMSOC21, 🟥 Level4

#900 Word Cloud (Python)
  Python/Word Cloud/README.md
  Python/Word Cloud/textfile.txt
  Python/Word Cloud/word_cloud.py
Labels: LGMSOC21, 🟨 Level2

#884 Added Text Editor in Python Scripts
  Python/Text Editor/Images/1.jpg
  Python/Text Editor/Images/10.jpg
  Python/Text Editor/Images/11.jpg
  Python/Text Editor/Images/12.jpg
  Python/Text Editor/Images/2.jpg
  Python/Text Editor/Images/3.jpg
  Python/Text Editor/Images/4.jpg
  Python/Text Editor/Images/5.jpg
  Python/Text Editor/Images/6.jpg
  Python/Text Editor/Images/7.jpg
  Python/Text Editor/Images/8.jpg
  Python/Text Editor/Images/9.jpg
  Python/Text Editor/Images/about.gif
  Python/Text Editor/Images/copy.gif
  Python/Text Editor/Images/cut.gif
  Python/Text Editor/Images/new_file.gif
  Python/Text Editor/Images/newfile.gif
  Python/Text Editor/Images/on_find.gif
  Python/Text Editor/Images/onfind.gif
  Python/Text Editor/Images/open_file.gif
  Python/Text Editor/Images/openfile.gif
  Python/Text Editor/Images/paste.gif
  Python/Text Editor/Images/redo.gif
  Python/Text Editor/Images/save.gif
  Python/Text Editor/Images/undo.gif
  Python/Text Editor/README.md
  Python/Text Editor/requirements.txt
  Python/Text Editor/text_editor.py
Labels: LGMSOC21, 🟥 Level4

#897 21 Number Game
  Python/21 Number Game/21_number_game.py
  Python/21 Number Game/photos/five.png
  Python/21 Number Game/photos/four.png
  Python/21 Number Game/photos/one.png
  Python/21 Number Game/photos/seven.png
  Python/21 Number Game/photos/six.png
  Python/21 Number Game/photos/three.png
  Python/21 Number Game/photos/two.png
  Python/21 Number Game/readme.md
Labels: LGMSOC21, 🟧 Level3

#882 Fix 829 add Text to speech
  C Sharp/Text to Speech/README.MD
  C Sharp/Text to Speech/pic.jpg
  C Sharp/Text to Speech/src/.vs/Text to Speech/v16/.suo
  C Sharp/Text to Speech/src/App.config
  C Sharp/Text to Speech/src/Form1.Designer.cs
  C Sharp/Text to Speech/src/Form1.cs
  C Sharp/Text to Speech/src/Form1.resx
  C Sharp/Text to Speech/src/Program.cs
  C Sharp/Text to Speech/src/Properties/AssemblyInfo.cs
  C Sharp/Text to Speech/src/Properties/Resources.Designer.cs
  C Sharp/Text to Speech/src/Properties/Resources.resx
  C Sharp/Text to Speech/src/Properties/Settings.Designer.cs
  C Sharp/Text to Speech/src/Properties/Settings.settings
  C Sharp/Text to Speech/src/Text to Speech.csproj
  C Sharp/Text to Speech/src/Text to Speech.sln
  C Sharp/Text to Speech/src/obj/Debug/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs
  C Sharp/Text to Speech/src/obj/Debug/DesignTimeResolveAssemblyReferences.cache
  C Sharp/Text to Speech/src/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  C Sharp/Text to Speech/src/obj/Debug/Text to Speech.csproj.AssemblyReference.cache
  C Sharp/Text to Speech/src/obj/Debug/Text to Speech.csproj.CoreCompileInputs.cache
  C Sharp/Text to Speech/src/obj/Debug/Text to Speech.csproj.FileListAbsolute.txt
  C Sharp/Text to Speech/src/obj/Debug/Text to Speech.csproj.GenerateResource.cache
  C Sharp/Text to Speech/src/obj/Debug/Text_to_Speech.Form1.resources
  C Sharp/Text to Speech/src/obj/Debug/Text_to_Speech.Properties.Resources.resources
Labels: LGMSOC21, 🟧 Level3

#912 Fix #906 - Added temperature converter
  Javascript/Temperature Converter/index.html
  Javascript/Temperature Converter/readme.md
  Javascript/Temperature Converter/script.js
  Javascript/Temperature Converter/style.css
Labels: LGMSOC21, 🟧 Level3

#883 Fixes #909 Spell correction.md
  Python/ATM Machine System/README.md
Labels: LGMSOC21, 🟪 Level0

#919 Added Piano Application in Python Scripts
  Python/Piano Application/Images/1.jpg
  Python/Piano Application/Images/2.jpg
  Python/Piano Application/Images/3.jpg
  Python/Piano Application/Images/piano.jpg
  Python/Piano Application/README.md
  Python/Piano Application/Sounds/Piano1.mp3
  Python/Piano Application/Sounds/Piano10.mp3
  Python/Piano Application/Sounds/Piano11.mp3
  Python/Piano Application/Sounds/Piano12.mp3
  Python/Piano Application/Sounds/Piano13.mp3
  Python/Piano Application/Sounds/Piano14.mp3
  Python/Piano Application/Sounds/Piano15.mp3
  Python/Piano Application/Sounds/Piano16.mp3
  Python/Piano Application/Sounds/Piano17.mp3
  Python/Piano Application/Sounds/Piano18.mp3
  Python/Piano Application/Sounds/Piano19.mp3
  Python/Piano Application/Sounds/Piano2.mp3
  Python/Piano Application/Sounds/Piano20.mp3
  Python/Piano Application/Sounds/Piano21.mp3
  Python/Piano Application/Sounds/Piano22.mp3
  Python/Piano Application/Sounds/Piano23.mp3
  Python/Piano Application/Sounds/Piano3.mp3
  Python/Piano Application/Sounds/Piano4.mp3
  Python/Piano Application/Sounds/Piano5.mp3
  Python/Piano Application/Sounds/Piano6.mp3
  Python/Piano Application/Sounds/Piano7.mp3
  Python/Piano Application/Sounds/Piano8.mp3
  Python/Piano Application/Sounds/Piano9.mp3
  Python/Piano Application/piano_application.py
  Python/Piano Application/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#915 Added Image Editor in Python Scripts
  Python/Image Editor/Images/1.jpg
  Python/Image Editor/Images/10.jpg
  Python/Image Editor/Images/11.jpg
  Python/Image Editor/Images/2.jpg
  Python/Image Editor/Images/3.jpg
  Python/Image Editor/Images/4.jpg
  Python/Image Editor/Images/5.jpg
  Python/Image Editor/Images/6.jpg
  Python/Image Editor/Images/7.jpg
  Python/Image Editor/Images/8.jpg
  Python/Image Editor/Images/9.jpg
  Python/Image Editor/Images/cartoon_edited.jpg
  Python/Image Editor/Images/parrot.jpg
  Python/Image Editor/Images/sketch_edited.jpg
  Python/Image Editor/README.md
  Python/Image Editor/image_editor.py
  Python/Image Editor/requirements.txt
Labels: LGMSOC21, 🟥 Level4

#905 Text File To PDF(Python)
  Python/Text File To PDF/README.md
  Python/Text File To PDF/main.py
  Python/Text File To PDF/myfile.txt
  Python/Text File To PDF/mypdf.pdf
Labels: LGMSOC21, 🟨 Level2

#920 Mastermind Game
  Python/MasterMind Game/Images/five.png
  Python/MasterMind Game/Images/four.png
  Python/MasterMind Game/Images/one.png
  Python/MasterMind Game/Images/three.png
  Python/MasterMind Game/Images/two.png
  Python/MasterMind Game/mastermind_game.py
  Python/MasterMind Game/readme.md
Labels: LGMSOC21, 🟨 Level2

#923 Added the files
  Python/Contact_Book/Output.jpg
  Python/Contact_Book/README.md
  Python/Contact_Book/code.py
Labels: LGMSOC21, 🟨 Level2

#946 BMI_Calculator
  C/BMI_Calculator/Output.jpg
  C/BMI_Calculator/README.md
  C/BMI_Calculator/main.c
Labels: LGMSOC21, 🟩 Level1

#944 Added Mouse Pointer Co-ordinates Getter in Python Scripts
  Python/Mouse Pointer Co-ordinates Getter/Images/1.jpg
  Python/Mouse Pointer Co-ordinates Getter/Images/2.jpg
  Python/Mouse Pointer Co-ordinates Getter/Images/3.jpg
  Python/Mouse Pointer Co-ordinates Getter/Images/4.jpg
  Python/Mouse Pointer Co-ordinates Getter/Images/5.jpg
  Python/Mouse Pointer Co-ordinates Getter/Images/6.jpg
  Python/Mouse Pointer Co-ordinates Getter/README.md
  Python/Mouse Pointer Co-ordinates Getter/mouse_pointer_co-ordinates_getter.py
  Python/Mouse Pointer Co-ordinates Getter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#926 Fix #904 Updated readme
  README.md
  assets/Logos/logohackingscript (1).png
  assets/Logos/logohackingscript.png
Labels: LGMSOC21, 🟩 Level1

#924 University Website
  Python/University Website/Images/attend.jpg
  Python/University Website/Images/course.jpg
  Python/University Website/Images/details.jpg
  Python/University Website/Images/fees.jpg
  Python/University Website/Images/home_page.jpg
  Python/University Website/Images/login.jpg
  Python/University Website/Images/register.jpg
  Python/University Website/Images/tt.jpg
  Python/University Website/README.md
  Python/University Website/application.py
  Python/University Website/forms.py
  Python/University Website/routes.py
  Python/University Website/student.sqlite3
  Python/University Website/templates/attendance.html
  Python/University Website/templates/base.html
  Python/University Website/templates/course.html
  Python/University Website/templates/details.html
  Python/University Website/templates/fees.html
  Python/University Website/templates/home.html
  Python/University Website/templates/login.html
  Python/University Website/templates/register.html
  Python/University Website/templates/result.html
  Python/University Website/templates/time_table.html
Labels: LGMSOC21, 🟥 Level4

#936 PNG To JPG Converter (Python)
  Python/PNG To JPG Converter/README.md
  Python/PNG To JPG Converter/main.py
Labels: LGMSOC21, 🟨 Level2

#943 Added the food recipe website
  Javascript/Food_recipe/README.md
  Javascript/Food_recipe/RecipeMania.ico
  Javascript/Food_recipe/Screenshot (273).png
  Javascript/Food_recipe/Screenshot (326).png
  Javascript/Food_recipe/food.jpg
  Javascript/Food_recipe/index.html
  Javascript/Food_recipe/myscript.js
  Javascript/Food_recipe/styles.css
Labels: LGMSOC21, 🟧 Level3

#955 Added Image Resizer in Python Scripts
  Python/Image Resizer/Images/1.jpg
  Python/Image Resizer/Images/2.jpg
  Python/Image Resizer/Images/3.jpg
  Python/Image Resizer/Images/4.jpg
  Python/Image Resizer/Images/5.jpg
  Python/Image Resizer/Images/6.jpg
  Python/Image Resizer/Images/7.jpg
  Python/Image Resizer/Images/8.jpg
  Python/Image Resizer/Images/9.jpg
  Python/Image Resizer/README.md
  Python/Image Resizer/image_resizer.py
  Python/Image Resizer/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#939 CSV to Excel Converter using Pandas in Python
  Python/Csv To excel/After.png
  Python/Csv To excel/Before.png
  Python/Csv To excel/img.jpg
  Python/Csv To excel/main.py
  Python/Csv To excel/readme.md
  Python/Csv To excel/test.csv
  Python/Csv To excel/test.csv.xlsx
Labels: LGMSOC21, 🟨 Level2

#952 Added Stone, Paper, Scissor in python
  Python/Stone, Paper, Scissor game/Images/img1.png
  Python/Stone, Paper, Scissor game/Images/img2.png
  Python/Stone, Paper, Scissor game/StonePaperScissor.py
  Python/Stone, Paper, Scissor game/readme.md
Labels: LGMSOC21, 🟨 Level2

#958 Pokemon Training Game
  C++/Pokemon Training Game/pictures/one.png
  C++/Pokemon Training Game/pictures/three.png
  C++/Pokemon Training Game/pictures/two.png
  C++/Pokemon Training Game/pokemon_training.cpp
  C++/Pokemon Training Game/readme.md
Labels: LGMSOC21, 🟩 Level1

#957 Added MP4 To MP3 Converter in Python Scripts
  Python/MP4 To MP3 Converter/Images/1.jpg
  Python/MP4 To MP3 Converter/Images/2.jpg
  Python/MP4 To MP3 Converter/Images/3.jpg
  Python/MP4 To MP3 Converter/Images/4.jpg
  Python/MP4 To MP3 Converter/Images/5.jpg
  Python/MP4 To MP3 Converter/Images/6.jpg
  Python/MP4 To MP3 Converter/Images/convert.jpg
  Python/MP4 To MP3 Converter/README.md
  Python/MP4 To MP3 Converter/mp4_to_mp3_converter.py
  Python/MP4 To MP3 Converter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#963 Github Bot
  Python/Github Bot/README.md
  Python/Github Bot/github_bot.py
Labels: LGMSOC21, 🟧 Level3

#966 Added bmi calculator Fixes #896
  Android Studio Scripts/BMIcalculator/.gitignore
  Android Studio Scripts/BMIcalculator/.idea/.gitignore
  Android Studio Scripts/BMIcalculator/.idea/compiler.xml
  Android Studio Scripts/BMIcalculator/.idea/gradle.xml
  Android Studio Scripts/BMIcalculator/.idea/jarRepositories.xml
  Android Studio Scripts/BMIcalculator/.idea/misc.xml
  Android Studio Scripts/BMIcalculator/.idea/runConfigurations.xml
  Android Studio Scripts/BMIcalculator/.idea/vcs.xml
  Android Studio Scripts/BMIcalculator/app/.gitignore
  Android Studio Scripts/BMIcalculator/app/build.gradle
  Android Studio Scripts/BMIcalculator/app/proguard-rules.pro
  Android Studio Scripts/BMIcalculator/app/src/androidTest/java/com/example/bmicalculator/ExampleInstrumentedTest.java
  Android Studio Scripts/BMIcalculator/app/src/main/AndroidManifest.xml
  Android Studio Scripts/BMIcalculator/app/src/main/java/com/example/bmicalculator/MainActivity.java
  Android Studio Scripts/BMIcalculator/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/drawable/ic_launcher_background.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/layout/activity_main.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android Studio Scripts/BMIcalculator/app/src/main/res/values-night/themes.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/values/colors.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/values/strings.xml
  Android Studio Scripts/BMIcalculator/app/src/main/res/values/themes.xml
  Android Studio Scripts/BMIcalculator/app/src/test/java/com/example/bmicalculator/ExampleUnitTest.java
  Android Studio Scripts/BMIcalculator/build.gradle
  Android Studio Scripts/BMIcalculator/gradle.properties
  Android Studio Scripts/BMIcalculator/gradle/wrapper/gradle-wrapper.properties
  Android Studio Scripts/BMIcalculator/gradlew
  Android Studio Scripts/BMIcalculator/gradlew.bat
  Android Studio Scripts/BMIcalculator/settings.gradle
Labels: LGMSOC21, 🟧 Level3

#965 Added EMI Calculator in Python Scripts
  Python/EMI Calculator/EMI_calculator.py
  Python/EMI Calculator/Images/1.jpg
  Python/EMI Calculator/Images/10.jpg
  Python/EMI Calculator/Images/2.jpg
  Python/EMI Calculator/Images/3.jpg
  Python/EMI Calculator/Images/4.jpg
  Python/EMI Calculator/Images/5.jpg
  Python/EMI Calculator/Images/6.jpg
  Python/EMI Calculator/Images/7.jpg
  Python/EMI Calculator/Images/8.jpg
  Python/EMI Calculator/Images/9.jpg
  Python/EMI Calculator/Images/EMI_pdf.png
  Python/EMI Calculator/Images/emi_front.jpg
  Python/EMI Calculator/README.md
  Python/EMI Calculator/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#968 Fix #961 Added JS BMI calc
  Javascript/BMI Calculator/index.html
  Javascript/BMI Calculator/readme.md
  Javascript/BMI Calculator/script.js
  Javascript/BMI Calculator/style.css
Labels: LGMSOC21, 🟧 Level3

#973 Image Cartoonifier added in Image Editor (Python)
  Python/Image Editor/Images/output(cartoon).png
  Python/Image Editor/README.md
  Python/Image Editor/image_cartoonifier.py
Labels: LGMSOC21, 🟩 Level1

#974 Integer to Roman Numerals
  Python/Integer to Roman Numerals/Images/output.png
  Python/Integer to Roman Numerals/README.md
  Python/Integer to Roman Numerals/integer _to_roman_numeral.py
Labels: LGMSOC21, 🟩 Level1

#975 2048 Game (Python)
  Python/2048 Game/2048_game.py
  Python/2048 Game/README.md
Labels: LGMSOC21, 🟧 Level3

#977 Added URL-Domain Extractor in Python Scripts
  Python/URL-Domain Extractor/Images/1.jpg
  Python/URL-Domain Extractor/Images/2.jpg
  Python/URL-Domain Extractor/Images/3.jpg
  Python/URL-Domain Extractor/Images/4.jpg
  Python/URL-Domain Extractor/Images/5.jpg
  Python/URL-Domain Extractor/Images/6.jpg
  Python/URL-Domain Extractor/README.md
  Python/URL-Domain Extractor/requirements.txt
  Python/URL-Domain Extractor/url-domain_extractor.py
Labels: LGMSOC21, 🟨 Level2

#979 Added Programming Language Detector in Python Scripts
  Python/Programming Language Detector/Images/1.jpg
  Python/Programming Language Detector/Images/10.jpg
  Python/Programming Language Detector/Images/2.jpg
  Python/Programming Language Detector/Images/3.jpg
  Python/Programming Language Detector/Images/4.jpg
  Python/Programming Language Detector/Images/5.jpg
  Python/Programming Language Detector/Images/6.jpg
  Python/Programming Language Detector/Images/7.jpg
  Python/Programming Language Detector/Images/8.jpg
  Python/Programming Language Detector/Images/9.jpg
  Python/Programming Language Detector/README.md
  Python/Programming Language Detector/programming_language_detector.py
  Python/Programming Language Detector/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#988 Added IP Address Extractor-Validator in Python Scripts
  Python/IP Address Extractor-Validator/IP_address_extractor-validator.py
  Python/IP Address Extractor-Validator/Images/1.jpg
  Python/IP Address Extractor-Validator/Images/10.jpg
  Python/IP Address Extractor-Validator/Images/11.jpg
  Python/IP Address Extractor-Validator/Images/12.jpg
  Python/IP Address Extractor-Validator/Images/13.jpg
  Python/IP Address Extractor-Validator/Images/2.jpg
  Python/IP Address Extractor-Validator/Images/3.jpg
  Python/IP Address Extractor-Validator/Images/4.jpg
  Python/IP Address Extractor-Validator/Images/5.jpg
  Python/IP Address Extractor-Validator/Images/6.jpg
  Python/IP Address Extractor-Validator/Images/7.jpg
  Python/IP Address Extractor-Validator/Images/8.jpg
  Python/IP Address Extractor-Validator/Images/9.jpg
  Python/IP Address Extractor-Validator/Images/front_ip.jpg
  Python/IP Address Extractor-Validator/Images/one.gif
  Python/IP Address Extractor-Validator/README.md
  Python/IP Address Extractor-Validator/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#991 Loan Calculator ( Python GUI)
  Python/Loan Calculator/README.md
  Python/Loan Calculator/loan_calculator.py
Labels: LGMSOC21, 🟨 Level2

#994 Added Absolute Time Delta in Python Scripts
  Python/Absolute Time Delta/Images/1.jpg
  Python/Absolute Time Delta/Images/2.jpg
  Python/Absolute Time Delta/Images/3.jpg
  Python/Absolute Time Delta/Images/4.jpg
  Python/Absolute Time Delta/Images/5.jpg
  Python/Absolute Time Delta/Images/6.jpg
  Python/Absolute Time Delta/Images/7.jpg
  Python/Absolute Time Delta/Images/8.jpg
  Python/Absolute Time Delta/README.md
  Python/Absolute Time Delta/absolute_time_delta.py
  Python/Absolute Time Delta/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#997 Countdown Timer (Javascript)
  Javascript/Countdown Timer/README.md
  Javascript/Countdown Timer/index.html
  Javascript/Countdown Timer/myscript.js
  Javascript/Countdown Timer/mystyle.css
Labels: LGMSOC21, 🟨 Level2

#925 Added preloader to the website
  Project Website/assets/Loader.webp
  Project Website/assets/css/style.css
  Project Website/index.html
Labels: LGMSOC21, 🟨 Level2

#999 Smart Calculator (Python GUI)
  Python/Smart Calculator/README.md
  Python/Smart Calculator/smart_calculator.py
Labels: LGMSOC21, 🟨 Level2

#1009 Moving Train Animation in C++ (#714)
  C++/MOVING TRAIN/README.md
  C++/MOVING TRAIN/main.cpp
Labels: LGMSOC21, 🟧 Level3

#1000 Added Hex Color Code in Python Scripts
  Python/Hex Color Code/Images/1.jpg
  Python/Hex Color Code/Images/2.jpg
  Python/Hex Color Code/Images/3.jpg
  Python/Hex Color Code/Images/4.jpg
  Python/Hex Color Code/Images/5.jpg
  Python/Hex Color Code/Images/6.jpg
  Python/Hex Color Code/Images/7.jpg
  Python/Hex Color Code/README.md
  Python/Hex Color Code/hex_color_code.py
  Python/Hex Color Code/hex_data.csv
  Python/Hex Color Code/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#1010 Added voice recorder using python
  Python/Voice Recorder/Images/img.png
  Python/Voice Recorder/Voice_recorder.py
  Python/Voice Recorder/readme.md
Labels: LGMSOC21, 🟨 Level2

#1013 PDF Merger (Python)
  Python/PDF Merger/README.md
  Python/PDF Merger/pdf_merger.py
Labels: LGMSOC21, 🟨 Level2

#1015 Book Store
  Python/Book Management System/.gitignore
  Python/Book Management System/Images/add.png
  Python/Book Management System/Images/delete.png
  Python/Book Management System/Images/home.png
  Python/Book Management System/Images/update.png
  Python/Book Management System/Images/view.png
  Python/Book Management System/README.md
  Python/Book Management System/book_gui.py
  Python/Book Management System/books.db
  Python/Book Management System/database.py
Labels: LGMSOC21, 🟥 Level4

#1016 Image Size Compressor (Python)
  Python/Image Size Compressor/README.md
  Python/Image Size Compressor/image_size_compressor.py
Labels: LGMSOC21, 🟩 Level1

#1020 Avatar Creator (Python)
  Python/Avatar Creator/README.md
  Python/Avatar Creator/avatar_creator.py
Labels: LGMSOC21, 🟨 Level2

#1018 Added Code Comments Fetcher in Python Scripts
  Python/Code Comments Fetcher/Images/1.jpg
  Python/Code Comments Fetcher/Images/10.jpg
  Python/Code Comments Fetcher/Images/2.jpg
  Python/Code Comments Fetcher/Images/3.jpg
  Python/Code Comments Fetcher/Images/4.jpg
  Python/Code Comments Fetcher/Images/5.jpg
  Python/Code Comments Fetcher/Images/6.jpg
  Python/Code Comments Fetcher/Images/7.jpg
  Python/Code Comments Fetcher/Images/8.jpg
  Python/Code Comments Fetcher/Images/9.jpg
  Python/Code Comments Fetcher/README.md
  Python/Code Comments Fetcher/code_comments_fetcher.py
  Python/Code Comments Fetcher/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#1026 Added Color Converter in Python Scripts
  Python/Color Converter/Images/1.jpg
  Python/Color Converter/Images/10.jpg
  Python/Color Converter/Images/2.jpg
  Python/Color Converter/Images/3.jpg
  Python/Color Converter/Images/4.jpg
  Python/Color Converter/Images/5.jpg
  Python/Color Converter/Images/6.jpg
  Python/Color Converter/Images/7.jpg
  Python/Color Converter/Images/8.jpg
  Python/Color Converter/Images/9.jpg
  Python/Color Converter/Images/color.png
  Python/Color Converter/README.md
  Python/Color Converter/color_converter.py
  Python/Color Converter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#1025 Telegram Bot (Python)
  Python/Telegram Bot/README.md
  Python/Telegram Bot/telegram_bot.py
Labels: LGMSOC21, 🟨 Level2

#1024 2048 Game Added
  Javascript/2048 Game/creative.gif
  Javascript/2048 Game/gameover.png
  Javascript/2048 Game/hello.js
  Javascript/2048 Game/index.html
  Javascript/2048 Game/initial.png
  Javascript/2048 Game/play.png
  Javascript/2048 Game/readme.md
  Javascript/2048 Game/style.css
Labels: LGMSOC21, 🟥 Level4

#1012 Currency Converter App
  Python/Currency Converter app/.gitignore
  Python/Currency Converter app/Images/forgot_password.png
  Python/Currency Converter app/Images/forgot_password_1.png
  Python/Currency Converter app/Images/forgot_password_2.png
  Python/Currency Converter app/Images/home.png
  Python/Currency Converter app/Images/home1.png
  Python/Currency Converter app/Images/login.png
  Python/Currency Converter app/Images/login1.png
  Python/Currency Converter app/Images/login2.png
  Python/Currency Converter app/Images/sign_up.png
  Python/Currency Converter app/Images/sign_up_success.png
  Python/Currency Converter app/README.md
  Python/Currency Converter app/currency.py
  Python/Currency Converter app/layout.kv
  Python/Currency Converter app/logo.png
Labels: LGMSOC21, 🟧 Level3

#987 #953 Sign up and Registration Form
  Reactjs/sign-in-and-register-form/README.md
  Reactjs/sign-in-and-register-form/api/config.env
  Reactjs/sign-in-and-register-form/api/db/conn.js
  Reactjs/sign-in-and-register-form/api/model/User.js
  Reactjs/sign-in-and-register-form/api/package-lock.json
  Reactjs/sign-in-and-register-form/api/package.json
  Reactjs/sign-in-and-register-form/api/route/auth.js
  Reactjs/sign-in-and-register-form/api/server.js
  Reactjs/sign-in-and-register-form/client/.gitignore
  Reactjs/sign-in-and-register-form/client/README.md
  Reactjs/sign-in-and-register-form/client/package-lock.json
  Reactjs/sign-in-and-register-form/client/package.json
  Reactjs/sign-in-and-register-form/client/public/favicon.ico
  Reactjs/sign-in-and-register-form/client/public/index.html
  Reactjs/sign-in-and-register-form/client/public/manifest.json
  Reactjs/sign-in-and-register-form/client/public/robots.txt
  Reactjs/sign-in-and-register-form/client/src/App.css
  Reactjs/sign-in-and-register-form/client/src/App.js
  Reactjs/sign-in-and-register-form/client/src/App.test.js
  Reactjs/sign-in-and-register-form/client/src/component/Home/Home.css
  Reactjs/sign-in-and-register-form/client/src/component/Home/Home.js
  Reactjs/sign-in-and-register-form/client/src/component/Sign up/Signup.css
  Reactjs/sign-in-and-register-form/client/src/component/Sign up/Signup.js
  Reactjs/sign-in-and-register-form/client/src/component/Signin/Signin.css
  Reactjs/sign-in-and-register-form/client/src/component/Signin/Signin.js
  Reactjs/sign-in-and-register-form/client/src/context/Action.js
  Reactjs/sign-in-and-register-form/client/src/context/Context.js
  Reactjs/sign-in-and-register-form/client/src/context/Reducer.js
  Reactjs/sign-in-and-register-form/client/src/index.css
  Reactjs/sign-in-and-register-form/client/src/index.js
  Reactjs/sign-in-and-register-form/client/src/logo.svg
  Reactjs/sign-in-and-register-form/client/src/reportWebVitals.js
  Reactjs/sign-in-and-register-form/client/src/setupTests.js
Labels: LGMSOC21, 🟥 Level4

#1029 Added Resume Generator in Python Scripts
  Python/Resume Generator/Images/1.jpg
  Python/Resume Generator/Images/10.jpg
  Python/Resume Generator/Images/11.jpg
  Python/Resume Generator/Images/12.jpg
  Python/Resume Generator/Images/13.jpg
  Python/Resume Generator/Images/14.jpg
  Python/Resume Generator/Images/2.jpg
  Python/Resume Generator/Images/3.jpg
  Python/Resume Generator/Images/4.jpg
  Python/Resume Generator/Images/5.jpg
  Python/Resume Generator/Images/6.jpg
  Python/Resume Generator/Images/7.jpg
  Python/Resume Generator/Images/8.jpg
  Python/Resume Generator/Images/9.jpg
  Python/Resume Generator/Images/My_Resume1.png
  Python/Resume Generator/Images/resume_front.png
  Python/Resume Generator/README.md
  Python/Resume Generator/requirements.txt
  Python/Resume Generator/resume_generator.py
Labels: LGMSOC21, 🟧 Level3

#1031 Pokedex GUI (Python)
  Python/Pokedex GUI/README.md
  Python/Pokedex GUI/pokedex_gui.py
Labels: LGMSOC21, 🟧 Level3

#1033 Added Regex Checker in Python Scripts
  Python/Regex Checker/Images/1.jpg
  Python/Regex Checker/Images/2.jpg
  Python/Regex Checker/Images/3.jpg
  Python/Regex Checker/Images/4.jpg
  Python/Regex Checker/Images/5.jpg
  Python/Regex Checker/Images/6.jpg
  Python/Regex Checker/Images/7.jpg
  Python/Regex Checker/Images/8.jpg
  Python/Regex Checker/Images/cheat_sheet.jpg
  Python/Regex Checker/Images/regex.gif
  Python/Regex Checker/README.md
  Python/Regex Checker/regex_checker.py
  Python/Regex Checker/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#1036 Zip File Creator (Python)
  Python/Zip File Creator/README.md
  Python/Zip File Creator/zip_file_creator.py
Labels: LGMSOC21, 🟪 Level0

#1039 Fixes #861 exercise tracker added
  Javascript/Exercise Tracker/App.css
  Javascript/Exercise Tracker/App.js
  Javascript/Exercise Tracker/README.md
  Javascript/Exercise Tracker/create-exercise.js
  Javascript/Exercise Tracker/exercise-list.js
  Javascript/Exercise Tracker/images/img (1).jpg
  Javascript/Exercise Tracker/images/img (2).jpg
  Javascript/Exercise Tracker/images/img (3).jpg
  Javascript/Exercise Tracker/images/img (4).jpg
  Javascript/Exercise Tracker/index.css
  Javascript/Exercise Tracker/index.html
  Javascript/Exercise Tracker/index.js
  Javascript/Exercise Tracker/navbar-component.js
Labels: LGMSOC21, 🟥 Level4

#1040 Added Sentence Segmenter in Python Scripts
  Python/Sentence Segmenter/Images/1.jpg
  Python/Sentence Segmenter/Images/2.jpg
  Python/Sentence Segmenter/Images/3.jpg
  Python/Sentence Segmenter/Images/4.jpg
  Python/Sentence Segmenter/Images/5.jpg
  Python/Sentence Segmenter/Images/6.jpg
  Python/Sentence Segmenter/Images/7.jpg
  Python/Sentence Segmenter/README.md
  Python/Sentence Segmenter/requirements.txt
  Python/Sentence Segmenter/sentence_segmenter.py
Labels: LGMSOC21, 🟧 Level3

#1043 Fixes #784 2D Fish game
  Javascript/Fish-game/README.md
  Javascript/Fish-game/image/img.jpg
  Javascript/Fish-game/index.html
  Javascript/Fish-game/script.js
  Javascript/Fish-game/style.css
Labels: LGMSOC21, 🟧 Level3
